In [7]:
import pandas as pd
import numpy as np

In [1]:
import subprocess

subprocess.run(["nvidia-smi"])

CompletedProcess(args=['nvidia-smi'], returncode=0)

In [2]:
import torch

print("PyTorch:", torch.__version__)
print("CUDA:", torch.cuda.is_available())


if torch.cuda.is_available():

    print(
        "GPU:",
        torch.cuda.get_device_name(0)
    )

    print(
        "VRAM:",
        round(
            torch.cuda.get_device_properties(
                0
            ).total_memory / 1024**3,
            2
        ),
        "GB"
    )

PyTorch: 2.11.0+cu128
CUDA: True
GPU: NVIDIA GeForce RTX 3050 6GB Laptop GPU
VRAM: 6.0 GB

In [3]:
%pip install -U \
    transformers==5.17.0 \
    datasets==5.0.1 \
    accelerate==1.15.0 \
    scikit-learn==1.6.1 \
    numpy==2.1.3 \
    pandas==2.2.3 \
    matplotlib==3.10.0 \
    seaborn==0.13.2 \
    onnx==1.23.0 \
    onnxruntime==1.30.0 \
    optimum==2.3.0 \
    safetensors==0.8.0

Collecting transformers==5.17.0
  Downloading transformers-5.17.0-py3-none-any.whl.metadata (32 kB)
Collecting datasets==5.0.1
  Downloading datasets-5.0.1-py3-none-any.whl.metadata (23 kB)
Collecting accelerate==1.15.0
  Downloading accelerate-1.15.0-py3-none-any.whl.metadata (19 kB)
Collecting scikit-learn==1.6.1
  Downloading scikit_learn-1.6.1-cp313-cp313-win_amd64.whl.metadata (15 kB)
Collecting numpy==2.1.3
  Downloading numpy-2.1.3-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting pandas==2.2.3
  Downloading pandas-2.2.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting matplotlib==3.10.0
  Downloading matplotlib-3.10.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: seaborn==0.13.2 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (0.13.2)
Collecting onnx==1.23.0
  Downloading onnx-1.23.0-cp312-abi3-win_amd64.whl.metadata (8.7 kB)
Collecting onnxruntime==1.30.0
  Downloading onnxruntime-1.30.0-cp313-cp313-win_amd64.whl.metadata (5.9 kB)
Requirement already satisfied: optimum==2.3.0 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (2.3.0)
Requirement already satisfied: safetensors==0.8.0 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (0.8.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from transformers==5.17.0) (1.19.0)
Requirement already satisfied: packaging>=20.0 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from transformers==5.17.0) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from transformers==5.17.0) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from transformers==5.17.0) (2026.5.9)
Collecting tokenizers<0.24.0,>=0.23.1 (from transformers==5.17.0)
  Downloading tokenizers-0.23.2-cp310-abi3-win_amd64.whl.metadata (10 kB)
Requirement already satisfied: typer in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from transformers==5.17.0) (0.25.1)
Requirement already satisfied: tqdm>=4.60 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from transformers==5.17.0) (4.68.2)
Requirement already satisfied: filelock in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from datasets==5.0.1) (3.29.0)
Requirement already satisfied: pyarrow>=21.0.0 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from datasets==5.0.1) (24.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from datasets==5.0.1) (0.4.1)
Requirement already satisfied: requests>=2.32.2 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from datasets==5.0.1) (2.34.2)
Requirement already satisfied: httpx<1.0.0 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from datasets==5.0.1) (0.27.2)
Requirement already satisfied: xxhash in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from datasets==5.0.1) (3.7.0)
Requirement already satisfied: multiprocess<0.70.20 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from datasets==5.0.1) (0.70.19)
Requirement already satisfied: fsspec<=2026.6.0,>=2023.1.0 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets==5.0.1) (2026.4.0)
Requirement already satisfied: psutil in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from accelerate==1.15.0) (7.2.2)
Requirement already satisfied: torch>=2.0.0 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from accelerate==1.15.0) (2.11.0+cu128)
Requirement already satisfied: scipy>=1.6.0 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from scikit-learn==1.6.1) (1.17.1)
Requirement already satisfied: joblib>=1.2.0 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from scikit-learn==1.6.1) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from scikit-learn==1.6.1) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from pandas==2.2.3) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from pandas==2.2.3) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from pandas==2.2.3) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from matplotlib==3.10.0) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from matplotlib==3.10.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from matplotlib==3.10.0) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from matplotlib==3.10.0) (1.5.0)
Requirement already satisfied: pillow>=8 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from matplotlib==3.10.0) (12.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from matplotlib==3.10.0) (3.3.2)
Requirement already satisfied: protobuf>=6.31.1 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from onnx==1.23.0) (6.33.6)
Requirement already satisfied: typing_extensions>=4.7.1 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from onnx==1.23.0) (4.15.0)
Requirement already satisfied: ml_dtypes>=0.5.4 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from onnx==1.23.0) (0.5.4)
Requirement already satisfied: flatbuffers in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from onnxruntime==1.30.0) (25.12.19)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets==5.0.1) (3.14.1)
Requirement already satisfied: anyio in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from httpx<1.0.0->datasets==5.0.1) (4.13.0)
Requirement already satisfied: certifi in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from httpx<1.0.0->datasets==5.0.1) (2026.5.20)
Requirement already satisfied: httpcore==1.* in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from httpx<1.0.0->datasets==5.0.1) (1.0.9)
Requirement already satisfied: idna in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from httpx<1.0.0->datasets==5.0.1) (3.18)
Requirement already satisfied: sniffio in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from httpx<1.0.0->datasets==5.0.1) (1.3.1)
Requirement already satisfied: h11>=0.16 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets==5.0.1) (0.16.0)
Requirement already satisfied: click>=8.4.0 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers==5.17.0) (8.4.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers==5.17.0) (1.5.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from typer->transformers==5.17.0) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from typer->transformers==5.17.0) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from typer->transformers==5.17.0) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets==5.0.1) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets==5.0.1) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets==5.0.1) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets==5.0.1) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets==5.0.1) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets==5.0.1) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets==5.0.1) (1.24.2)
Requirement already satisfied: colorama in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from click>=8.4.0->huggingface-hub<2.0,>=1.5.0->transformers==5.17.0) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas==2.2.3) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from requests>=2.32.2->datasets==5.0.1) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from requests>=2.32.2->datasets==5.0.1) (2.7.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from rich>=13.8.0->typer->transformers==5.17.0) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from rich>=13.8.0->typer->transformers==5.17.0) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers==5.17.0) (0.1.2)
Requirement already satisfied: setuptools<82 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from torch>=2.0.0->accelerate==1.15.0) (78.1.0)
Requirement already satisfied: sympy>=1.13.3 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from torch>=2.0.0->accelerate==1.15.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from torch>=2.0.0->accelerate==1.15.0) (3.6.1)
Requirement already satisfied: jinja2 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from torch>=2.0.0->accelerate==1.15.0) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate==1.15.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages (from jinja2->torch>=2.0.0->accelerate==1.15.0) (3.0.3)
Downloading transformers-5.17.0-py3-none-any.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------- ----------------------- 5.0/12.3 MB 25.1 MB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 29.9 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 28.6 MB/s  0:00:00
Downloading datasets-5.0.1-py3-none-any.whl (559 kB)
   ---------------------------------------- 0.0/559.1 kB ? eta -:--:--
   ---------------------------------------- 559.1/559.1 kB 29.8 MB/s  0:00:00
Downloading accelerate-1.15.0-py3-none-any.whl (394 kB)
Downloading scikit_learn-1.6.1-cp313-cp313-win_amd64.whl (11.1 MB)
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   --------------------- ------------------ 6.0/11.1 MB 30.7 MB/s eta 0:00:01
   ---------------------------------------- 11.1/11.1 MB 30.7 MB/s  0:00:00
Downloading numpy-2.1.3-cp313-cp313-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ------------------- -------------------- 6.0/12.6 MB 31.3 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 31.3 MB/s  0:00:00
Downloading pandas-2.2.3-cp313-cp313-win_amd64.whl (11.5 MB)
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ----------------------- ---------------- 6.8/11.5 MB 34.6 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 31.2 MB/s  0:00:00
Downloading matplotlib-3.10.0-cp313-cp313-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ----------------------------------- ---- 7.1/8.0 MB 35.3 MB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 32.7 MB/s  0:00:00
Downloading onnx-1.23.0-cp312-abi3-win_amd64.whl (7.9 MB)
   ---------------------------------------- 0.0/7.9 MB ? eta -:--:--
   --------------------------------- ------ 6.6/7.9 MB 34.0 MB/s eta 0:00:01
   ---------------------------------------- 7.9/7.9 MB 32.6 MB/s  0:00:00
Downloading onnxruntime-1.30.0-cp313-cp313-win_amd64.whl (14.3 MB)
   ---------------------------------------- 0.0/14.3 MB ? eta -:--:--
   ------------------ --------------------- 6.6/14.3 MB 34.1 MB/s eta 0:00:01
   -------------------------------------- - 13.6/14.3 MB 33.4 MB/s eta 0:00:01
   ---------------------------------------- 14.3/14.3 MB 32.0 MB/s  0:00:00
Downloading tokenizers-0.23.2-cp310-abi3-win_amd64.whl (2.9 MB)
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   ---------------------------------------- 2.9/2.9 MB 25.7 MB/s  0:00:00
Installing collected packages: numpy, pandas, onnxruntime, scikit-learn, onnx, matplotlib, tokenizers, datasets, accelerate, transformers

  Attempting uninstall: numpy

    Found existing installation: numpy 2.4.4

    Uninstalling numpy-2.4.4:

   ----------------------------------------  0/10 [numpy]
      Successfully uninstalled numpy-2.4.4
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
   ----------------------------------------  0/10 [numpy]
  Attempting uninstall: pandas
   ----------------------------------------  0/10 [numpy]
    Found existing installation: pandas 3.0.3

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages\~-mpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\LOQ\Downloads\Python_programs\venv\Lib\site-packages\~-mpy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradio 6.18.0 requires fastapi<1.0,>=0.115.2, but you have fastapi 0.115.0 which is incompatible.
gradio 6.18.0 requires python-multipart<1.0,>=0.0.18, but you have python-multipart 0.0.12 which is incompatible.
gradio 6.18.0 requires starlette<2.0,>=1.0.1, but you have starlette 0.38.6 which is incompatible.
langchain-community 0.4.2 requires langchain-core<2.0.0,>=1.4.0, but you have langchain-core 0.3.25 which is incompatible.
langchain-community 0.4.2 requires pydantic-settings<3.0.0,>=2.10.1, but you have pydantic-settings 2.5.2 which is incompatible.
streamlit 1.58.0 requires starlette>=0.40.0, but you have starlette 0.38.6 which is incompatible.

In [4]:
from pathlib import Path
import random
import json
import os

import numpy as np
import torch


SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

PROJECT = Path.cwd()

DATA_DIR = (
    PROJECT /
    "client_pii_data"
)

MODEL_DIR = (
    PROJECT /
    "client_models" /
    "pii_ner"
)

CHECKPOINT_DIR = (
    PROJECT /
    "client_models" /
    "checkpoints" /
    "pii_ner"
)

REPORT_DIR = (
    PROJECT /
    "client_models" /
    "reports" /
    "pii_ner"
)

for path in [
    DATA_DIR,
    MODEL_DIR,
    CHECKPOINT_DIR,
    REPORT_DIR
]:

    path.mkdir(
        parents=True,
        exist_ok=True
    )


print("Data:", DATA_DIR)
print("Model:", MODEL_DIR)

Data: c:\Users\LOQ\Downloads\Python_programs\privacy-vision-browser-agent\model_train\client_pii_data
Model: c:\Users\LOQ\Downloads\Python_programs\privacy-vision-browser-agent\model_train\client_models\pii_ner

In [6]:
from datasets import load_dataset

webpii = load_dataset(
    "WebPII/webpii"
)

print(webpii)

AttributeError: module 'numpy' has no attribute '_no_nep50_warning'

In [ ]:
print(
    webpii["train"].features
)

print(
    webpii["train"][0]
)

{'image': Image(mode=None, decode=True), 'source_id': Value('string'), 'variant': Value('string'), 'page_type': Value('string'), 'company': Value('string'), 'image_width': Value('int64'), 'image_height': Value('int64'), 'num_pii_elements': Value('int64'), 'num_product_elements': Value('int64'), 'num_order_elements': Value('int64'), 'num_search_elements': Value('int64'), 'num_misc_elements': Value('int64'), 'fillable_count': Value('int64'), 'pii_elements_json': Value('string'), 'product_elements_json': Value('string'), 'order_elements_json': Value('string'), 'search_elements_json': Value('string'), 'misc_elements_json': Value('string')}
{'image': <PIL.PngImagePlugin.PngImageFile image mode=RGB size=1280x1396 at 0x7FDEAF613CB0>, 'source_id': '3900', 'variant': 'full', 'page_type': 'address-validator', 'company': 'walmart', 'image_width': 1280, 'image_height': 1396, 'num_pii_elements': 12, 'num_product_elements': 0, 'num_order_elements': 0, 'num_search_elements': 0, 'num_misc_elements': 0, 'fillable_count': 10, 'pii_elements_json': '[{"key": "PII_CITY_STATE_ZIP", "value": "Ryanbury, MT 36716", "bbox_x": 905, "bbox_y": 201.25, "bbox_width": 145.03125, "bbox_height": 16, "visible": true, "clipped": false, "element_type": "text"}, {"key": "PII_DELIVERY_INSTRUCTIONS", "value": "Place behind screen door", "bbox_x": 52, "bbox_y": 1059, "bbox_width": 496, "bbox_height": 120, "visible": true, "clipped": true, "element_type": "input"}, {"key": "PII_STATE_ABBR", "value": "MT", "bbox_x": 52, "bbox_y": 768, "bbox_width": 238.078125, "bbox_height": 52, "visible": true, "clipped": true, "element_type": "input"}, {"key": "PII_STREET", "value": "275 Sara Summit", "bbox_x": 905, "bbox_y": 180.25, "bbox_width": 121.84375, "bbox_height": 16, "visible": true, "clipped": false, "element_type": "text"}, {"key": "PII_STREET", "value": "275 Sara Summit", "bbox_x": 52, "bbox_y": 477, "bbox_width": 496, "bbox_height": 52, "visible": true, "clipped": false, "element_type": "input"}, {"key": "PII_FIRSTNAME", "value": "Angela", "bbox_x": 52, "bbox_y": 283, "bbox_width": 496, "bbox_height": 52, "visible": true, "clipped": false, "element_type": "input"}, {"key": "PII_LASTNAME", "value": "Ayers", "bbox_x": 52, "bbox_y": 380, "bbox_width": 496, "bbox_height": 52, "visible": true, "clipped": false, "element_type": "input"}, {"key": "PII_STREET2", "value": "4320 Campbell Trace Apt. 081", "bbox_x": 52, "bbox_y": 574, "bbox_width": 496, "bbox_height": 52, "visible": true, "clipped": false, "element_type": "input"}, {"key": "PII_CITY", "value": "Ryanbury", "bbox_x": 52, "bbox_y": 671, "bbox_width": 496, "bbox_height": 52, "visible": true, "clipped": false, "element_type": "input"}, {"key": "PII_POSTCODE", "value": "36716", "bbox_x": 306.078125, "bbox_y": 768, "bbox_width": 188.46875, "bbox_height": 52, "visible": true, "clipped": true, "element_type": "input"}, {"key": "PII_PHONE", "value": "9796964318", "bbox_x": 52, "bbox_y": 865, "bbox_width": 496, "bbox_height": 52, "visible": true, "clipped": true, "element_type": "input"}, {"key": "PII_SECURITY_CODE", "value": "58FG", "bbox_x": 52, "bbox_y": 962, "bbox_width": 496, "bbox_height": 52, "visible": true, "clipped": true, "element_type": "input"}]', 'product_elements_json': '[]', 'order_elements_json': '[]', 'search_elements_json': '[]', 'misc_elements_json': '[]'}

In [ ]:
print("Available splits:")

for split_name in webpii.keys():
    print(
        split_name,
        len(webpii[split_name])
    )

Available splits:
train 40384
test 4481

In [ ]:
print(
    webpii["train"].features
)

{'image': Image(mode=None, decode=True), 'source_id': Value('string'), 'variant': Value('string'), 'page_type': Value('string'), 'company': Value('string'), 'image_width': Value('int64'), 'image_height': Value('int64'), 'num_pii_elements': Value('int64'), 'num_product_elements': Value('int64'), 'num_order_elements': Value('int64'), 'num_search_elements': Value('int64'), 'num_misc_elements': Value('int64'), 'fillable_count': Value('int64'), 'pii_elements_json': Value('string'), 'product_elements_json': Value('string'), 'order_elements_json': Value('string'), 'search_elements_json': Value('string'), 'misc_elements_json': Value('string')}

In [ ]:
sample = webpii["train"][0]

print(
    sample.keys()
)

print(sample)

dict_keys(['image', 'source_id', 'variant', 'page_type', 'company', 'image_width', 'image_height', 'num_pii_elements', 'num_product_elements', 'num_order_elements', 'num_search_elements', 'num_misc_elements', 'fillable_count', 'pii_elements_json', 'product_elements_json', 'order_elements_json', 'search_elements_json', 'misc_elements_json'])
{'image': <PIL.PngImagePlugin.PngImageFile image mode=RGB size=1280x1396 at 0x7FDEAF65EE90>, 'source_id': '3900', 'variant': 'full', 'page_type': 'address-validator', 'company': 'walmart', 'image_width': 1280, 'image_height': 1396, 'num_pii_elements': 12, 'num_product_elements': 0, 'num_order_elements': 0, 'num_search_elements': 0, 'num_misc_elements': 0, 'fillable_count': 10, 'pii_elements_json': '[{"key": "PII_CITY_STATE_ZIP", "value": "Ryanbury, MT 36716", "bbox_x": 905, "bbox_y": 201.25, "bbox_width": 145.03125, "bbox_height": 16, "visible": true, "clipped": false, "element_type": "text"}, {"key": "PII_DELIVERY_INSTRUCTIONS", "value": "Place behind screen door", "bbox_x": 52, "bbox_y": 1059, "bbox_width": 496, "bbox_height": 120, "visible": true, "clipped": true, "element_type": "input"}, {"key": "PII_STATE_ABBR", "value": "MT", "bbox_x": 52, "bbox_y": 768, "bbox_width": 238.078125, "bbox_height": 52, "visible": true, "clipped": true, "element_type": "input"}, {"key": "PII_STREET", "value": "275 Sara Summit", "bbox_x": 905, "bbox_y": 180.25, "bbox_width": 121.84375, "bbox_height": 16, "visible": true, "clipped": false, "element_type": "text"}, {"key": "PII_STREET", "value": "275 Sara Summit", "bbox_x": 52, "bbox_y": 477, "bbox_width": 496, "bbox_height": 52, "visible": true, "clipped": false, "element_type": "input"}, {"key": "PII_FIRSTNAME", "value": "Angela", "bbox_x": 52, "bbox_y": 283, "bbox_width": 496, "bbox_height": 52, "visible": true, "clipped": false, "element_type": "input"}, {"key": "PII_LASTNAME", "value": "Ayers", "bbox_x": 52, "bbox_y": 380, "bbox_width": 496, "bbox_height": 52, "visible": true, "clipped": false, "element_type": "input"}, {"key": "PII_STREET2", "value": "4320 Campbell Trace Apt. 081", "bbox_x": 52, "bbox_y": 574, "bbox_width": 496, "bbox_height": 52, "visible": true, "clipped": false, "element_type": "input"}, {"key": "PII_CITY", "value": "Ryanbury", "bbox_x": 52, "bbox_y": 671, "bbox_width": 496, "bbox_height": 52, "visible": true, "clipped": false, "element_type": "input"}, {"key": "PII_POSTCODE", "value": "36716", "bbox_x": 306.078125, "bbox_y": 768, "bbox_width": 188.46875, "bbox_height": 52, "visible": true, "clipped": true, "element_type": "input"}, {"key": "PII_PHONE", "value": "9796964318", "bbox_x": 52, "bbox_y": 865, "bbox_width": 496, "bbox_height": 52, "visible": true, "clipped": true, "element_type": "input"}, {"key": "PII_SECURITY_CODE", "value": "58FG", "bbox_x": 52, "bbox_y": 962, "bbox_width": 496, "bbox_height": 52, "visible": true, "clipped": true, "element_type": "input"}]', 'product_elements_json': '[]', 'order_elements_json': '[]', 'search_elements_json': '[]', 'misc_elements_json': '[]'}

In [ ]:
import json

for i in range(3):

    print(
        "\n===================="
    )

    print("RECORD", i)

    print(
        json.dumps(
            webpii["train"][i],
            indent=2,
            ensure_ascii=False,
            default=str
        )
    )

====================
RECORD 0
{
  "image": "<PIL.PngImagePlugin.PngImageFile image mode=RGB size=1280x1396 at 0x7FDEAF65F610>",
  "source_id": "3900",
  "variant": "full",
  "page_type": "address-validator",
  "company": "walmart",
  "image_width": 1280,
  "image_height": 1396,
  "num_pii_elements": 12,
  "num_product_elements": 0,
  "num_order_elements": 0,
  "num_search_elements": 0,
  "num_misc_elements": 0,
  "fillable_count": 10,
  "pii_elements_json": "[{\"key\": \"PII_CITY_STATE_ZIP\", \"value\": \"Ryanbury, MT 36716\", \"bbox_x\": 905, \"bbox_y\": 201.25, \"bbox_width\": 145.03125, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_DELIVERY_INSTRUCTIONS\", \"value\": \"Place behind screen door\", \"bbox_x\": 52, \"bbox_y\": 1059, \"bbox_width\": 496, \"bbox_height\": 120, \"visible\": true, \"clipped\": true, \"element_type\": \"input\"}, {\"key\": \"PII_STATE_ABBR\", \"value\": \"MT\", \"bbox_x\": 52, \"bbox_y\": 768, \"bbox_width\": 238.078125, \"bbox_height\": 52, \"visible\": true, \"clipped\": true, \"element_type\": \"input\"}, {\"key\": \"PII_STREET\", \"value\": \"275 Sara Summit\", \"bbox_x\": 905, \"bbox_y\": 180.25, \"bbox_width\": 121.84375, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_STREET\", \"value\": \"275 Sara Summit\", \"bbox_x\": 52, \"bbox_y\": 477, \"bbox_width\": 496, \"bbox_height\": 52, \"visible\": true, \"clipped\": false, \"element_type\": \"input\"}, {\"key\": \"PII_FIRSTNAME\", \"value\": \"Angela\", \"bbox_x\": 52, \"bbox_y\": 283, \"bbox_width\": 496, \"bbox_height\": 52, \"visible\": true, \"clipped\": false, \"element_type\": \"input\"}, {\"key\": \"PII_LASTNAME\", \"value\": \"Ayers\", \"bbox_x\": 52, \"bbox_y\": 380, \"bbox_width\": 496, \"bbox_height\": 52, \"visible\": true, \"clipped\": false, \"element_type\": \"input\"}, {\"key\": \"PII_STREET2\", \"value\": \"4320 Campbell Trace Apt. 081\", \"bbox_x\": 52, \"bbox_y\": 574, \"bbox_width\": 496, \"bbox_height\": 52, \"visible\": true, \"clipped\": false, \"element_type\": \"input\"}, {\"key\": \"PII_CITY\", \"value\": \"Ryanbury\", \"bbox_x\": 52, \"bbox_y\": 671, \"bbox_width\": 496, \"bbox_height\": 52, \"visible\": true, \"clipped\": false, \"element_type\": \"input\"}, {\"key\": \"PII_POSTCODE\", \"value\": \"36716\", \"bbox_x\": 306.078125, \"bbox_y\": 768, \"bbox_width\": 188.46875, \"bbox_height\": 52, \"visible\": true, \"clipped\": true, \"element_type\": \"input\"}, {\"key\": \"PII_PHONE\", \"value\": \"9796964318\", \"bbox_x\": 52, \"bbox_y\": 865, \"bbox_width\": 496, \"bbox_height\": 52, \"visible\": true, \"clipped\": true, \"element_type\": \"input\"}, {\"key\": \"PII_SECURITY_CODE\", \"value\": \"58FG\", \"bbox_x\": 52, \"bbox_y\": 962, \"bbox_width\": 496, \"bbox_height\": 52, \"visible\": true, \"clipped\": true, \"element_type\": \"input\"}]",
  "product_elements_json": "[]",
  "order_elements_json": "[]",
  "search_elements_json": "[]",
  "misc_elements_json": "[]"
}

====================
RECORD 1
{
  "image": "<PIL.PngImagePlugin.PngImageFile image mode=RGB size=1280x1394 at 0x7FDEAF66A9E0>",
  "source_id": "5300",
  "variant": "full",
  "page_type": "newsletter-management",
  "company": "ulta-beauty",
  "image_width": 1280,
  "image_height": 1394,
  "num_pii_elements": 4,
  "num_product_elements": 0,
  "num_order_elements": 0,
  "num_search_elements": 1,
  "num_misc_elements": 0,
  "fillable_count": 0,
  "pii_elements_json": "[{\"key\": \"PII_EMAIL\", \"value\": \"michaelmoore@hotmail.com\", \"bbox_x\": 348.21875, \"bbox_y\": 478.5, \"bbox_width\": 201.296875, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_FIRSTNAME\", \"value\": \"Michael\", \"bbox_x\": 1004.625, \"bbox_y\": 26.25, \"bbox_width\": 49.796875, \"bbox_height\": 15, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_FIRSTNAME\", \"value\": \"MICHAEL\", \"bbox_x\": 747.203125, \"bbox_y\": 325.5, \"bbox_width\": 154.90625, \"bbox_height\": 33, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_FULLNAME\", \"value\": \"Michael Moore\", \"bbox_x\": 290.484375, \"bbox_y\": 449.5, \"bbox_width\": 101.34375, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}]",
  "product_elements_json": "[]",
  "order_elements_json": "[]",
  "search_elements_json": "[{\"key\": \"HEADER_SEARCH\", \"value\": \"Search\", \"bbox_x\": 188.796875, \"bbox_y\": 16, \"bbox_width\": 200, \"bbox_height\": 36, \"visible\": true, \"clipped\": false, \"element_type\": \"input\"}]",
  "misc_elements_json": "[]"
}

====================
RECORD 2
{
  "image": "<PIL.PngImagePlugin.PngImageFile image mode=RGB size=1280x941 at 0x7FDEAF66A9E0>",
  "source_id": "6075",
  "variant": "full",
  "page_type": "store-pickup",
  "company": "lowes",
  "image_width": 1280,
  "image_height": 941,
  "num_pii_elements": 18,
  "num_product_elements": 0,
  "num_order_elements": 1,
  "num_search_elements": 2,
  "num_misc_elements": 0,
  "fillable_count": 1,
  "pii_elements_json": "[{\"key\": \"PII_CITY\", \"value\": \"West Brucestad\", \"bbox_x\": 52, \"bbox_y\": 51, \"bbox_width\": 109.671875, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_CITY\", \"value\": \"West Brucestad\", \"bbox_x\": 52, \"bbox_y\": 370.59375, \"bbox_width\": 109.671875, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_CITY\", \"value\": \"West Brucestad\", \"bbox_x\": 52, \"bbox_y\": 328, \"bbox_width\": 141.90625, \"bbox_height\": 19, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_CITY2\", \"value\": \"Howeburgh\", \"bbox_x\": 52, \"bbox_y\": 684.78125, \"bbox_width\": 80.1875, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_CITY2\", \"value\": \"Howeburgh\", \"bbox_x\": 52, \"bbox_y\": 642.1875, \"bbox_width\": 103.59375, \"bbox_height\": 19, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_LOCATION1_STREET\", \"value\": \"615 French Squares\", \"bbox_x\": 52, \"bbox_y\": 351, \"bbox_width\": 138.75, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_LOCATION2_POSTCODE\", \"value\": \"28749\", \"bbox_x\": 165.1875, \"bbox_y\": 684.78125, \"bbox_width\": 44.546875, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_LOCATION2_STREET\", \"value\": \"37739 Ariana Views\", \"bbox_x\": 52, \"bbox_y\": 665.1875, \"bbox_width\": 139.21875, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_PHONE\", \"value\": \"9197059905\", \"bbox_x\": 134, \"bbox_y\": 518.1875, \"bbox_width\": 89.078125, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_POSTCODE\", \"value\": \"27649\", \"bbox_x\": 257, \"bbox_y\": 70.5, \"bbox_width\": 44.546875, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_POSTCODE\", \"value\": \"27649\", \"bbox_x\": 194.671875, \"bbox_y\": 370.59375, \"bbox_width\": 44.546875, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_POSTCODE\", \"value\": \"27649\", \"bbox_x\": 192.546875, \"bbox_y\": 278, \"bbox_width\": 44.546875, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_STATE_ABBR\", \"value\": \"DE\", \"bbox_x\": 170.578125, \"bbox_y\": 370.59375, \"bbox_width\": 19.640625, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_POSTCODE3\", \"value\": \"27649\", \"bbox_x\": 50, \"bbox_y\": 177, \"bbox_width\": 235, \"bbox_height\": 44, \"visible\": true, \"clipped\": false, \"element_type\": \"input\"}, {\"key\": \"PII_POSTCODE_FULL\", \"value\": \"27649\", \"bbox_x\": 192.546875, \"bbox_y\": 278, \"bbox_width\": 44.546875, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_POSTCODE_NUMERIC\", \"value\": \"27649\", \"bbox_x\": 192.546875, \"bbox_y\": 278, \"bbox_width\": 44.546875, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_STATE_ABBR2\", \"value\": \"DE\", \"bbox_x\": 141.09375, \"bbox_y\": 684.78125, \"bbox_width\": 19.640625, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_MAP\", \"value\": \"\", \"bbox_x\": 380, \"bbox_y\": 159, \"bbox_width\": 900, \"bbox_height\": 782.375, \"visible\": true, \"clipped\": true, \"element_type\": \"text\"}]",
  "product_elements_json": "[]",
  "order_elements_json": "[{\"key\": \"ORDER_NUM_ITEMS\", \"value\": \"1\", \"bbox_x\": 1246.5, \"bbox_y\": 110, \"bbox_width\": 6.96875, \"bbox_height\": 11, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}]",
  "search_elements_json": "[{\"key\": \"HEADER_SEARCH\", \"value\": \"What are you looking for\", \"bbox_x\": 529.375, \"bbox_y\": 111.25, \"bbox_width\": 247, \"bbox_height\": 37, \"visible\": true, \"clipped\": false, \"element_type\": \"input\"}, {\"key\": \"SEARCH_STORE_LOCATION\", \"value\": \"27649\", \"bbox_x\": 50, \"bbox_y\": 177, \"bbox_width\": 235, \"bbox_height\": 44, \"visible\": true, \"clipped\": false, \"element_type\": \"input\"}]",
  "misc_elements_json": "[]"
}

In [ ]:
for i in range(5):

    print(
        "\nRECORD",
        i
    )

    print(
        json.dumps(
            webpii["train"][i],
            indent=2,
            default=str
        )
    )

RECORD 0
{
  "image": "<PIL.PngImagePlugin.PngImageFile image mode=RGB size=1280x1396 at 0x7FDEAF66A9E0>",
  "source_id": "3900",
  "variant": "full",
  "page_type": "address-validator",
  "company": "walmart",
  "image_width": 1280,
  "image_height": 1396,
  "num_pii_elements": 12,
  "num_product_elements": 0,
  "num_order_elements": 0,
  "num_search_elements": 0,
  "num_misc_elements": 0,
  "fillable_count": 10,
  "pii_elements_json": "[{\"key\": \"PII_CITY_STATE_ZIP\", \"value\": \"Ryanbury, MT 36716\", \"bbox_x\": 905, \"bbox_y\": 201.25, \"bbox_width\": 145.03125, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_DELIVERY_INSTRUCTIONS\", \"value\": \"Place behind screen door\", \"bbox_x\": 52, \"bbox_y\": 1059, \"bbox_width\": 496, \"bbox_height\": 120, \"visible\": true, \"clipped\": true, \"element_type\": \"input\"}, {\"key\": \"PII_STATE_ABBR\", \"value\": \"MT\", \"bbox_x\": 52, \"bbox_y\": 768, \"bbox_width\": 238.078125, \"bbox_height\": 52, \"visible\": true, \"clipped\": true, \"element_type\": \"input\"}, {\"key\": \"PII_STREET\", \"value\": \"275 Sara Summit\", \"bbox_x\": 905, \"bbox_y\": 180.25, \"bbox_width\": 121.84375, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_STREET\", \"value\": \"275 Sara Summit\", \"bbox_x\": 52, \"bbox_y\": 477, \"bbox_width\": 496, \"bbox_height\": 52, \"visible\": true, \"clipped\": false, \"element_type\": \"input\"}, {\"key\": \"PII_FIRSTNAME\", \"value\": \"Angela\", \"bbox_x\": 52, \"bbox_y\": 283, \"bbox_width\": 496, \"bbox_height\": 52, \"visible\": true, \"clipped\": false, \"element_type\": \"input\"}, {\"key\": \"PII_LASTNAME\", \"value\": \"Ayers\", \"bbox_x\": 52, \"bbox_y\": 380, \"bbox_width\": 496, \"bbox_height\": 52, \"visible\": true, \"clipped\": false, \"element_type\": \"input\"}, {\"key\": \"PII_STREET2\", \"value\": \"4320 Campbell Trace Apt. 081\", \"bbox_x\": 52, \"bbox_y\": 574, \"bbox_width\": 496, \"bbox_height\": 52, \"visible\": true, \"clipped\": false, \"element_type\": \"input\"}, {\"key\": \"PII_CITY\", \"value\": \"Ryanbury\", \"bbox_x\": 52, \"bbox_y\": 671, \"bbox_width\": 496, \"bbox_height\": 52, \"visible\": true, \"clipped\": false, \"element_type\": \"input\"}, {\"key\": \"PII_POSTCODE\", \"value\": \"36716\", \"bbox_x\": 306.078125, \"bbox_y\": 768, \"bbox_width\": 188.46875, \"bbox_height\": 52, \"visible\": true, \"clipped\": true, \"element_type\": \"input\"}, {\"key\": \"PII_PHONE\", \"value\": \"9796964318\", \"bbox_x\": 52, \"bbox_y\": 865, \"bbox_width\": 496, \"bbox_height\": 52, \"visible\": true, \"clipped\": true, \"element_type\": \"input\"}, {\"key\": \"PII_SECURITY_CODE\", \"value\": \"58FG\", \"bbox_x\": 52, \"bbox_y\": 962, \"bbox_width\": 496, \"bbox_height\": 52, \"visible\": true, \"clipped\": true, \"element_type\": \"input\"}]",
  "product_elements_json": "[]",
  "order_elements_json": "[]",
  "search_elements_json": "[]",
  "misc_elements_json": "[]"
}

RECORD 1
{
  "image": "<PIL.PngImagePlugin.PngImageFile image mode=RGB size=1280x1394 at 0x7FDEAF66A9E0>",
  "source_id": "5300",
  "variant": "full",
  "page_type": "newsletter-management",
  "company": "ulta-beauty",
  "image_width": 1280,
  "image_height": 1394,
  "num_pii_elements": 4,
  "num_product_elements": 0,
  "num_order_elements": 0,
  "num_search_elements": 1,
  "num_misc_elements": 0,
  "fillable_count": 0,
  "pii_elements_json": "[{\"key\": \"PII_EMAIL\", \"value\": \"michaelmoore@hotmail.com\", \"bbox_x\": 348.21875, \"bbox_y\": 478.5, \"bbox_width\": 201.296875, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_FIRSTNAME\", \"value\": \"Michael\", \"bbox_x\": 1004.625, \"bbox_y\": 26.25, \"bbox_width\": 49.796875, \"bbox_height\": 15, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_FIRSTNAME\", \"value\": \"MICHAEL\", \"bbox_x\": 747.203125, \"bbox_y\": 325.5, \"bbox_width\": 154.90625, \"bbox_height\": 33, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_FULLNAME\", \"value\": \"Michael Moore\", \"bbox_x\": 290.484375, \"bbox_y\": 449.5, \"bbox_width\": 101.34375, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}]",
  "product_elements_json": "[]",
  "order_elements_json": "[]",
  "search_elements_json": "[{\"key\": \"HEADER_SEARCH\", \"value\": \"Search\", \"bbox_x\": 188.796875, \"bbox_y\": 16, \"bbox_width\": 200, \"bbox_height\": 36, \"visible\": true, \"clipped\": false, \"element_type\": \"input\"}]",
  "misc_elements_json": "[]"
}

RECORD 2
{
  "image": "<PIL.PngImagePlugin.PngImageFile image mode=RGB size=1280x941 at 0x7FDEAF66A9E0>",
  "source_id": "6075",
  "variant": "full",
  "page_type": "store-pickup",
  "company": "lowes",
  "image_width": 1280,
  "image_height": 941,
  "num_pii_elements": 18,
  "num_product_elements": 0,
  "num_order_elements": 1,
  "num_search_elements": 2,
  "num_misc_elements": 0,
  "fillable_count": 1,
  "pii_elements_json": "[{\"key\": \"PII_CITY\", \"value\": \"West Brucestad\", \"bbox_x\": 52, \"bbox_y\": 51, \"bbox_width\": 109.671875, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_CITY\", \"value\": \"West Brucestad\", \"bbox_x\": 52, \"bbox_y\": 370.59375, \"bbox_width\": 109.671875, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_CITY\", \"value\": \"West Brucestad\", \"bbox_x\": 52, \"bbox_y\": 328, \"bbox_width\": 141.90625, \"bbox_height\": 19, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_CITY2\", \"value\": \"Howeburgh\", \"bbox_x\": 52, \"bbox_y\": 684.78125, \"bbox_width\": 80.1875, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_CITY2\", \"value\": \"Howeburgh\", \"bbox_x\": 52, \"bbox_y\": 642.1875, \"bbox_width\": 103.59375, \"bbox_height\": 19, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_LOCATION1_STREET\", \"value\": \"615 French Squares\", \"bbox_x\": 52, \"bbox_y\": 351, \"bbox_width\": 138.75, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_LOCATION2_POSTCODE\", \"value\": \"28749\", \"bbox_x\": 165.1875, \"bbox_y\": 684.78125, \"bbox_width\": 44.546875, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_LOCATION2_STREET\", \"value\": \"37739 Ariana Views\", \"bbox_x\": 52, \"bbox_y\": 665.1875, \"bbox_width\": 139.21875, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_PHONE\", \"value\": \"9197059905\", \"bbox_x\": 134, \"bbox_y\": 518.1875, \"bbox_width\": 89.078125, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_POSTCODE\", \"value\": \"27649\", \"bbox_x\": 257, \"bbox_y\": 70.5, \"bbox_width\": 44.546875, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_POSTCODE\", \"value\": \"27649\", \"bbox_x\": 194.671875, \"bbox_y\": 370.59375, \"bbox_width\": 44.546875, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_POSTCODE\", \"value\": \"27649\", \"bbox_x\": 192.546875, \"bbox_y\": 278, \"bbox_width\": 44.546875, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_STATE_ABBR\", \"value\": \"DE\", \"bbox_x\": 170.578125, \"bbox_y\": 370.59375, \"bbox_width\": 19.640625, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_POSTCODE3\", \"value\": \"27649\", \"bbox_x\": 50, \"bbox_y\": 177, \"bbox_width\": 235, \"bbox_height\": 44, \"visible\": true, \"clipped\": false, \"element_type\": \"input\"}, {\"key\": \"PII_POSTCODE_FULL\", \"value\": \"27649\", \"bbox_x\": 192.546875, \"bbox_y\": 278, \"bbox_width\": 44.546875, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_POSTCODE_NUMERIC\", \"value\": \"27649\", \"bbox_x\": 192.546875, \"bbox_y\": 278, \"bbox_width\": 44.546875, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_STATE_ABBR2\", \"value\": \"DE\", \"bbox_x\": 141.09375, \"bbox_y\": 684.78125, \"bbox_width\": 19.640625, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_MAP\", \"value\": \"\", \"bbox_x\": 380, \"bbox_y\": 159, \"bbox_width\": 900, \"bbox_height\": 782.375, \"visible\": true, \"clipped\": true, \"element_type\": \"text\"}]",
  "product_elements_json": "[]",
  "order_elements_json": "[{\"key\": \"ORDER_NUM_ITEMS\", \"value\": \"1\", \"bbox_x\": 1246.5, \"bbox_y\": 110, \"bbox_width\": 6.96875, \"bbox_height\": 11, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}]",
  "search_elements_json": "[{\"key\": \"HEADER_SEARCH\", \"value\": \"What are you looking for\", \"bbox_x\": 529.375, \"bbox_y\": 111.25, \"bbox_width\": 247, \"bbox_height\": 37, \"visible\": true, \"clipped\": false, \"element_type\": \"input\"}, {\"key\": \"SEARCH_STORE_LOCATION\", \"value\": \"27649\", \"bbox_x\": 50, \"bbox_y\": 177, \"bbox_width\": 235, \"bbox_height\": 44, \"visible\": true, \"clipped\": false, \"element_type\": \"input\"}]",
  "misc_elements_json": "[]"
}

RECORD 3
{
  "image": "<PIL.PngImagePlugin.PngImageFile image mode=RGB size=1280x1595 at 0x7FDEAF66A9E0>",
  "source_id": "2725",
  "variant": "full",
  "page_type": "newsletter-management",
  "company": "slack",
  "image_width": 1280,
  "image_height": 1595,
  "num_pii_elements": 1,
  "num_product_elements": 0,
  "num_order_elements": 0,
  "num_search_elements": 0,
  "num_misc_elements": 0,
  "fillable_count": 0,
  "pii_elements_json": "[{\"key\": \"PII_EMAIL\", \"value\": \"agreene@yahoo.com\", \"bbox_x\": 491.84375, \"bbox_y\": 1517.125, \"bbox_width\": 176.171875, \"bbox_height\": 18, \"visible\": true, \"clipped\": true, \"element_type\": \"text\"}]",
  "product_elements_json": "[]",
  "order_elements_json": "[]",
  "search_elements_json": "[]",
  "misc_elements_json": "[]"
}

RECORD 4
{
  "image": "<PIL.PngImagePlugin.PngImageFile image mode=RGB size=1280x2557 at 0x7FDEAF66A9E0>",
  "source_id": "8775",
  "variant": "full",
  "page_type": "receipt",
  "company": "crate-barrel",
  "image_width": 1280,
  "image_height": 2557,
  "num_pii_elements": 17,
  "num_product_elements": 9,
  "num_order_elements": 6,
  "num_search_elements": 1,
  "num_misc_elements": 1,
  "fillable_count": 1,
  "pii_elements_json": "[{\"key\": \"PII_CARD_LAST4\", \"value\": \"3944\", \"bbox_x\": 726.5, \"bbox_y\": 1299.96875, \"bbox_width\": 35.640625, \"bbox_height\": 16, \"visible\": true, \"clipped\": true, \"element_type\": \"text\"}, {\"key\": \"PII_CARD_TYPE\", \"value\": \"Visa\", \"bbox_x\": 672, \"bbox_y\": 1299.96875, \"bbox_width\": 29.046875, \"bbox_height\": 16, \"visible\": true, \"clipped\": true, \"element_type\": \"text\"}, {\"key\": \"PII_CITY\", \"value\": \"Chamberstown\", \"bbox_x\": 230, \"bbox_y\": 1190.078125, \"bbox_width\": 98.25, \"bbox_height\": 15, \"visible\": true, \"clipped\": true, \"element_type\": \"text\"}, {\"key\": \"PII_COUNTRY\", \"value\": \"United States\", \"bbox_x\": 672, \"bbox_y\": 1210.875, \"bbox_width\": 88.03125, \"bbox_height\": 15, \"visible\": true, \"clipped\": true, \"element_type\": \"text\"}, {\"key\": \"PII_EMAIL\", \"value\": \"megan.rice@yahoo.com\", \"bbox_x\": 384.03125, \"bbox_y\": 567.28125, \"bbox_width\": 187.9375, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"PII_FULLNAME\", \"value\": \"Megan Rice\", \"bbox_x\": 230, \"bbox_y\": 1137.28125, \"bbox_width\": 104.125, \"bbox_height\": 19, \"visible\": true, \"clipped\": true, \"element_type\": \"text\"}, {\"key\": \"PII_LOGIN_PASSWORD\", \"value\": \"#96YY)En!I0D4\", \"bbox_x\": 790, \"bbox_y\": 370.5, \"bbox_width\": 300, \"bbox_height\": 47, \"visible\": true, \"clipped\": false, \"element_type\": \"input\"}, {\"key\": \"PII_PHONE\", \"value\": \"5269190534\", \"bbox_x\": 230, \"bbox_y\": 1210.875, \"bbox_width\": 82.71875, \"bbox_height\": 15, \"visible\": true, \"clipped\": true, \"element_type\": \"text\"}, {\"key\": \"PII_POSTCODE\", \"value\": \"31554\", \"bbox_x\": 359.421875, \"bbox_y\": 1190.078125, \"bbox_width\": 41.359375, \"bbox_height\": 15, \"visible\": true, \"clipped\": true, \"element_type\": \"text\"}, {\"key\": \"PII_STATE_ABBR\", \"value\": \"OK\", \"bbox_x\": 336.515625, \"bbox_y\": 1190.078125, \"bbox_width\": 18.765625, \"bbox_height\": 15, \"visible\": true, \"clipped\": true, \"element_type\": \"text\"}, {\"key\": \"PII_STREET\", \"value\": \"757 Lamb Knolls\", \"bbox_x\": 230, \"bbox_y\": 1169.28125, \"bbox_width\": 107.921875, \"bbox_height\": 15, \"visible\": true, \"clipped\": true, \"element_type\": \"text\"}, {\"key\": \"PII_FULLNAME2\", \"value\": \"Megan Rice\", \"bbox_x\": 672, \"bbox_y\": 1137.28125, \"bbox_width\": 104.125, \"bbox_height\": 19, \"visible\": true, \"clipped\": true, \"element_type\": \"text\"}, {\"key\": \"PII_STREET2\", \"value\": \"757 Lamb Knolls\", \"bbox_x\": 672, \"bbox_y\": 1169.28125, \"bbox_width\": 107.921875, \"bbox_height\": 15, \"visible\": true, \"clipped\": true, \"element_type\": \"text\"}, {\"key\": \"PII_CITY2\", \"value\": \"Chamberstown\", \"bbox_x\": 672, \"bbox_y\": 1190.078125, \"bbox_width\": 98.25, \"bbox_height\": 15, \"visible\": true, \"clipped\": true, \"element_type\": \"text\"}, {\"key\": \"PII_STATE_ABBR2\", \"value\": \"OK\", \"bbox_x\": 778.515625, \"bbox_y\": 1190.078125, \"bbox_width\": 18.765625, \"bbox_height\": 15, \"visible\": true, \"clipped\": true, \"element_type\": \"text\"}, {\"key\": \"PII_POSTCODE2\", \"value\": \"31554\", \"bbox_x\": 801.421875, \"bbox_y\": 1190.078125, \"bbox_width\": 41.359375, \"bbox_height\": 15, \"visible\": true, \"clipped\": true, \"element_type\": \"text\"}, {\"key\": \"PII_PHONE2\", \"value\": \"5269190534\", \"bbox_x\": 672, \"bbox_y\": 1231.671875, \"bbox_width\": 82.71875, \"bbox_height\": 15, \"visible\": true, \"clipped\": true, \"element_type\": \"text\"}]",
  "product_elements_json": "[{\"key\": \"PRODUCT1_NAME\", \"value\": \"Women's Mules with Suede Cross-Over Upper, Brown (Beige), 8 UK\", \"bbox_x\": 340, \"bbox_y\": 1414.96875, \"bbox_width\": 527.5, \"bbox_height\": 16, \"visible\": true, \"clipped\": true, \"element_type\": \"text\"}, {\"key\": \"PRODUCT1_PRICE\", \"value\": 43.79, \"bbox_x\": 413.953125, \"bbox_y\": 1439.96875, \"bbox_width\": 45.5, \"bbox_height\": 15, \"visible\": true, \"clipped\": true, \"element_type\": \"text\"}, {\"key\": \"PRODUCT1_QUANTITY\", \"value\": 2, \"bbox_x\": 370.59375, \"bbox_y\": 1459.46875, \"bbox_width\": 8.28125, \"bbox_height\": 15, \"visible\": true, \"clipped\": true, \"element_type\": \"text\"}, {\"key\": \"PRODUCT1_IMAGE\", \"value\": \"\", \"bbox_x\": 240.375, \"bbox_y\": 1412.96875, \"bbox_width\": 69.25, \"bbox_height\": 89.984375, \"visible\": true, \"clipped\": true, \"element_type\": \"image\"}, {\"key\": \"PRODUCT2_IMAGE\", \"value\": \"\", \"bbox_x\": 176, \"bbox_y\": 1751.46875, \"bbox_width\": 175, \"bbox_height\": 175, \"visible\": true, \"clipped\": true, \"element_type\": \"image\"}, {\"key\": \"PRODUCT3_IMAGE\", \"value\": \"\", \"bbox_x\": 357, \"bbox_y\": 1751.46875, \"bbox_width\": 175, \"bbox_height\": 175, \"visible\": true, \"clipped\": true, \"element_type\": \"image\"}, {\"key\": \"PRODUCT4_IMAGE\", \"value\": \"\", \"bbox_x\": 538, \"bbox_y\": 1751.46875, \"bbox_width\": 175, \"bbox_height\": 175, \"visible\": true, \"clipped\": true, \"element_type\": \"image\"}, {\"key\": \"PRODUCT5_IMAGE\", \"value\": \"\", \"bbox_x\": 719, \"bbox_y\": 1751.46875, \"bbox_width\": 175, \"bbox_height\": 175, \"visible\": true, \"clipped\": true, \"element_type\": \"image\"}, {\"key\": \"PRODUCT6_IMAGE\", \"value\": \"\", \"bbox_x\": 900, \"bbox_y\": 1751.46875, \"bbox_width\": 175, \"bbox_height\": 175, \"visible\": true, \"clipped\": true, \"element_type\": \"image\"}]",
  "order_elements_json": "[{\"key\": \"ORDER_NUM_ITEMS\", \"value\": \"0\", \"bbox_x\": 1255.703125, \"bbox_y\": 67.25, \"bbox_width\": 8.28125, \"bbox_height\": 15, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"ORDER_ID\", \"value\": \"478069878\", \"bbox_x\": 488.859375, \"bbox_y\": 653.28125, \"bbox_width\": 87.671875, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"ORDER_DATE\", \"value\": \"7/10/2024\", \"bbox_x\": 482.21875, \"bbox_y\": 678.28125, \"bbox_width\": 78.421875, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"ORDER_TOTAL\", \"value\": \"$87.58\", \"bbox_x\": 494.03125, \"bbox_y\": 703.28125, \"bbox_width\": 54.046875, \"bbox_height\": 16, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}, {\"key\": \"ORDER_ITEM_TOTAL\", \"value\": \"$87.58\", \"bbox_x\": 378.875, \"bbox_y\": 1478.96875, \"bbox_width\": 45.5, \"bbox_height\": 15, \"visible\": true, \"clipped\": true, \"element_type\": \"text\"}, {\"key\": \"ORDER_DELIVERY_DATE\", \"value\": \"Sun, 7/14 \\u2013 Tue, 7/16\", \"bbox_x\": 283.953125, \"bbox_y\": 1570.96875, \"bbox_width\": 136.640625, \"bbox_height\": 15, \"visible\": true, \"clipped\": true, \"element_type\": \"text\"}]",
  "search_elements_json": "[{\"key\": \"HEADER_SEARCH\", \"value\": \"Search\", \"bbox_x\": 16, \"bbox_y\": 55.5, \"bbox_width\": 150, \"bbox_height\": 39, \"visible\": true, \"clipped\": false, \"element_type\": \"input\"}]",
  "misc_elements_json": "[{\"key\": \"FAVORITES_COUNT\", \"value\": \"0\", \"bbox_x\": 1203.421875, \"bbox_y\": 67.25, \"bbox_width\": 8.28125, \"bbox_height\": 15, \"visible\": true, \"clipped\": false, \"element_type\": \"text\"}]"
}

In [ ]:
for split in webpii.keys():

    print(
        split,
        len(webpii[split])
    )

train 40384
test 4481

In [ ]:
sample = webpii[
    "train"
][0]

print(
    sample.keys()
)

dict_keys(['image', 'source_id', 'variant', 'page_type', 'company', 'image_width', 'image_height', 'num_pii_elements', 'num_product_elements', 'num_order_elements', 'num_search_elements', 'num_misc_elements', 'fillable_count', 'pii_elements_json', 'product_elements_json', 'order_elements_json', 'search_elements_json', 'misc_elements_json'])

In [ ]:
SEMANTIC_PII = [
    "PERSON",
    "LOCATION",
    "ADDRESS",
    "ORGANIZATION"
]

In [ ]:
REGEX_PII = [
    "EMAIL",
    "PHONE",
    "CARD",
    "IP_ADDRESS",
    "URL",
    "SECRET"
]

In [ ]:
LABEL_TYPES = [
    "PERSON",
    "LOCATION",
    "ADDRESS",
    "ORGANIZATION",
    "EMAIL",
    "PHONE",
    "CARD",
    "IP_ADDRESS",
    "URL",
    "SECRET"
]

LABELS = ["O"] + [
    prefix + "-" + label
    for label in LABEL_TYPES
    for prefix in ["B", "I"]
]

label2id = {
    label: i
    for i, label in enumerate(LABELS)
}

id2label = {
    i: label
    for label, i in label2id.items()
}

print(label2id)

{'O': 0, 'B-PERSON': 1, 'I-PERSON': 2, 'B-LOCATION': 3, 'I-LOCATION': 4, 'B-ADDRESS': 5, 'I-ADDRESS': 6, 'B-ORGANIZATION': 7, 'I-ORGANIZATION': 8, 'B-EMAIL': 9, 'I-EMAIL': 10, 'B-PHONE': 11, 'I-PHONE': 12, 'B-CARD': 13, 'I-CARD': 14, 'B-IP_ADDRESS': 15, 'I-IP_ADDRESS': 16, 'B-URL': 17, 'I-URL': 18, 'B-SECRET': 19, 'I-SECRET': 20}

In [ ]:
{
    "tokens": [
        "Aarav",
        "Sharma",
        "lives",
        "in",
        "Bengaluru"
    ],

    "ner_tags": [
        "B-PERSON",
        "I-PERSON",
        "O",
        "O",
        "B-LOCATION"
    ]
}

{'tokens': ['Aarav', 'Sharma', 'lives', 'in', 'Bengaluru'],
 'ner_tags': ['B-PERSON', 'I-PERSON', 'O', 'O', 'B-LOCATION']}

In [ ]:
import json

from datasets import Dataset

NORMALIZED_DIR = DATA_DIR / "normalized"
NORMALIZED_DIR.mkdir(parents=True, exist_ok=True)


def pii_key_to_label(key):
    key = key.upper()

    if "EMAIL" in key:
        return "EMAIL"
    if "PHONE" in key or "TEL" in key:
        return "PHONE"
    if "CARD" in key or "CREDIT" in key or "DEBIT" in key:
        return "CARD"
    if "IP" in key:
        return "IP_ADDRESS"
    if "URL" in key or "LINK" in key:
        return "URL"
    if any(part in key for part in [
        "PASSWORD", "PASSCODE", "SECRET", "TOKEN", "API_KEY",
        "SECURITY", "CREDENTIAL", "AUTH"
    ]):
        return "SECRET"
    if any(part in key for part in ["FIRSTNAME", "LASTNAME", "FULLNAME", "PERSON"]):
        return "PERSON"
    if any(part in key for part in ["CITY", "STATE", "COUNTRY", "POSTCODE", "ZIP", "LOCATION"]):
        return "LOCATION"
    if any(part in key for part in ["STREET", "ADDRESS", "DELIVERY"]):
        return "ADDRESS"
    if any(part in key for part in ["COMPANY", "ORGANIZATION", "ORG"]):
        return "ORGANIZATION"

    return None


def parse_elements(raw_elements):
    if not raw_elements:
        return []
    if isinstance(raw_elements, str):
        try:
            return json.loads(raw_elements)
        except json.JSONDecodeError:
            return []
    return raw_elements


normalized_records = []
source_dataset = webpii["train"].remove_columns(["image"])

for record in source_dataset:
    context_tokens = [
        "page",
        *str(record.get("page_type", "")).replace("-", " ").split(),
        "site",
        *str(record.get("company", "")).replace("-", " ").split(),
        "visible",
        "browser",
        "form"
    ]
    tokens = context_tokens[:]
    ner_tags = ["O"] * len(tokens)

    seen = set()
    pii_elements = parse_elements(record.get("pii_elements_json"))

    for element in pii_elements:
        value = str(element.get("value", "")).strip()
        key = str(element.get("key", ""))
        label = pii_key_to_label(key)

        if not value or label is None or (label, value) in seen:
            continue

        seen.add((label, value))
        field_tokens = [
            "field",
            *key.replace("PII_", "").replace("_", " ").lower().split(),
            "element",
            str(element.get("element_type", "text")).lower(),
            "value"
        ]
        tokens.extend(field_tokens)
        ner_tags.extend(["O"] * len(field_tokens))

        value_tokens = value.split()
        tokens.extend(value_tokens)
        ner_tags.extend(
            [f"B-{label}"] + [f"I-{label}"] * (len(value_tokens) - 1)
        )

    if tokens and len(tokens) == len(ner_tags):
        normalized_records.append({
            "tokens": tokens,
            "ner_tags": ner_tags
        })

normalized = Dataset.from_list(normalized_records)

print("Normalized rows:", len(normalized))
print("Labels present:", sorted({tag for row in normalized["ner_tags"] for tag in row}))
print(normalized.features)

Normalized rows: 40384
Labels present: ['B-ADDRESS', 'B-CARD', 'B-EMAIL', 'B-IP_ADDRESS', 'B-LOCATION', 'B-ORGANIZATION', 'B-PERSON', 'B-PHONE', 'B-SECRET', 'I-ADDRESS', 'I-CARD', 'I-IP_ADDRESS', 'I-LOCATION', 'I-ORGANIZATION', 'I-PERSON', 'I-PHONE', 'O']
{'tokens': List(Value('string')), 'ner_tags': List(Value('string'))}

In [ ]:
def make_plain_language_example(label, value):
    templates = {
        "PERSON": ["contact", value, "about", "the", "request"],
        "LOCATION": ["the", "user", "is", "in", value],
        "ADDRESS": ["deliver", "the", "package", "to", value],
        "ORGANIZATION": ["the", "account", "belongs", "to", value],
        "EMAIL": ["send", "a", "message", "to", value],
        "PHONE": ["call", value, "for", "verification"],
        "CARD": ["the", "payment", "card", "ends", "in", value],
        "IP_ADDRESS": ["the", "request", "came", "from", value],
        "URL": ["open", value, "in", "the", "browser"],
        "SECRET": ["enter", "the", "password", value, "to", "continue"]
    }
    tokens = templates[label]
    value_tokens = value.split()
    value_start = tokens.index(value)
    tags = ["O"] * len(tokens)
    tags[value_start:value_start + len(value_tokens)] = (
        [f"B-{label}"] + [f"I-{label}"] * (len(value_tokens) - 1)
    )
    return {"tokens": tokens, "ner_tags": tags}


plain_language_records = []
for record in source_dataset:
    seen_values = set()
    for element in parse_elements(record.get("pii_elements_json")):
        value = str(element.get("value", "")).strip()
        label = pii_key_to_label(str(element.get("key", "")))
        if not value or label is None or (label, value) in seen_values:
            continue
        seen_values.add((label, value))
        plain_language_records.append(make_plain_language_example(label, value))
        if len(seen_values) >= 2:
            break

normalized = Dataset.from_list(normalized_records + plain_language_records)
print(
    "Context-aware rows:", len(normalized_records),
    "plain-language rows:", len(plain_language_records),
    "combined rows:", len(normalized)
)

Context-aware rows: 40384 plain-language rows: 77212 combined rows: 117596

In [ ]:
split1 = normalized.train_test_split(
    test_size=0.20,
    seed=SEED
)

train_ds = split1["train"]
remaining = split1["test"]

split2 = remaining.train_test_split(
    test_size=0.50,
    seed=SEED
)

val_ds = split2["train"]
test_ds = split2["test"]

print(
    "Split sizes:",
    len(train_ds),
    len(val_ds),
    len(test_ds)
)

Split sizes: 94076 11760 11760

In [ ]:
BASE_MODEL = (
    "microsoft/deberta-v3-small"
)

In [ ]:
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification
)

BASE_MODEL = (
    "microsoft/deberta-v3-small"
)

tokenizer = (
    AutoTokenizer
    .from_pretrained(
        BASE_MODEL,
        use_fast=True
    )
)

In [ ]:
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification
)

BASE_MODEL = (
    "microsoft/deberta-v3-small"
)

tokenizer = (
    AutoTokenizer
    .from_pretrained(
        BASE_MODEL,
        use_fast=True
    )
)

torch.manual_seed(SEED)
model = (
    AutoModelForTokenClassification
    .from_pretrained(
        BASE_MODEL,
        num_labels=len(LABELS),
        id2label=id2label,
        label2id=label2id
    )
)

assert all(
    torch.isfinite(parameter).all().item()
    for parameter in model.parameters()
), "Fresh model contains non-finite parameters"

print(
    "Parameters:",
    sum(
        p.numel()
        for p in model.parameters()
    )
)

Loading weights:   0%|          | 0/102 [00:00<?, ?it/s]

[transformers] DebertaV2ForTokenClassification LOAD REPORT from: microsoft/deberta-v3-small
Key                                     | Status     |
----------------------------------------+------------+-
mask_predictions.LayerNorm.bias         | UNEXPECTED |
lm_predictions.lm_head.bias             | UNEXPECTED |
lm_predictions.lm_head.dense.bias       | UNEXPECTED |
mask_predictions.dense.weight           | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias   | UNEXPECTED |
lm_predictions.lm_head.dense.weight     | UNEXPECTED |
mask_predictions.classifier.bias        | UNEXPECTED |
mask_predictions.LayerNorm.weight       | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight | UNEXPECTED |
mask_predictions.classifier.weight      | UNEXPECTED |
mask_predictions.dense.bias             | UNEXPECTED |
classifier.bias                         | MISSING    |
classifier.weight                       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Parameters: 141320469

In [ ]:
# One-step CUDA stability probe for the local optimizer path.
probe_model = (
    AutoModelForTokenClassification
    .from_pretrained(
        BASE_MODEL,
        num_labels=len(LABELS),
        id2label=id2label,
        label2id=label2id
    )
)
probe_model.to("cuda" if use_cuda else "cpu")
probe_model.train()
probe_optimizer = torch.optim.SGD(
    probe_model.parameters(),
    lr=1e-5
)
probe_keys = ["input_ids", "attention_mask", "labels"]
probe_batch = data_collator([
    {key: tokenized_train[index][key] for key in probe_keys}
    for index in range(2)
])
probe_batch = {
    key: value.to(probe_model.device)
    for key, value in probe_batch.items()
}
probe_optimizer.zero_grad(set_to_none=True)
probe_output = probe_model(**probe_batch)
probe_loss = probe_output.loss
logits_finite_before_backward = torch.isfinite(probe_output.logits).all().item()
probe_loss.backward()
gradients = [
    parameter.grad
    for parameter in probe_model.parameters()
    if parameter.grad is not None
]
gradients_finite = all(torch.isfinite(gradient).all().item() for gradient in gradients)
gradient_norm = torch.nn.utils.clip_grad_norm_(probe_model.parameters(), 1.0)
probe_optimizer.step()

print(
    "probe_loss=", float(probe_loss.detach().cpu()),
    "logits_finite=", logits_finite_before_backward,
    "gradients_finite=", gradients_finite,
    "gradient_norm=", float(gradient_norm),
    "probe_finite=",
    all(torch.isfinite(parameter).all().item() for parameter in probe_model.parameters())
)

Loading weights:   0%|          | 0/102 [00:00<?, ?it/s]

[transformers] DebertaV2ForTokenClassification LOAD REPORT from: microsoft/deberta-v3-small
Key                                     | Status     |
----------------------------------------+------------+-
mask_predictions.LayerNorm.bias         | UNEXPECTED |
lm_predictions.lm_head.bias             | UNEXPECTED |
lm_predictions.lm_head.dense.bias       | UNEXPECTED |
mask_predictions.dense.weight           | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias   | UNEXPECTED |
lm_predictions.lm_head.dense.weight     | UNEXPECTED |
mask_predictions.classifier.bias        | UNEXPECTED |
mask_predictions.LayerNorm.weight       | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight | UNEXPECTED |
mask_predictions.classifier.weight      | UNEXPECTED |
mask_predictions.dense.bias             | UNEXPECTED |
classifier.bias                         | MISSING    |
classifier.weight                       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

probe_loss= 2.96875 logits_finite= True gradients_finite= True gradient_norm= 25.28125 probe_finite= True

In [22]:
def tokenize_and_align_labels(
    examples
):

    tokenized = tokenizer(
        examples["tokens"],

        truncation=True,

        max_length=256,

        is_split_into_words=True
    )

    aligned_labels = []

    for batch_index, tags in enumerate(
        examples["ner_tags"]
    ):

        word_ids = (
            tokenized.word_ids(
                batch_index=batch_index
            )
        )

        previous_word = None

        label_ids = []

        for word_id in word_ids:

            if word_id is None:

                label_ids.append(-100)

            elif word_id != previous_word:

                tag = tags[word_id]

                label_ids.append(
                    label2id[tag]
                )

            else:

                # Ignore subsequent subwords
                # to prevent overweighting.
                label_ids.append(-100)

            previous_word = word_id

        aligned_labels.append(
            label_ids
        )

    tokenized[
        "labels"
    ] = aligned_labels

    return tokenized

In [67]:
tokenized_train = (
    train_ds.map(
        tokenize_and_align_labels,
        batched=True,
        remove_columns=train_ds.column_names
    )
)

tokenized_val = (
    val_ds.map(
        tokenize_and_align_labels,
        batched=True,
        remove_columns=val_ds.column_names
    )
)

tokenized_test = (
    test_ds.map(
        tokenize_and_align_labels,
        batched=True,
        remove_columns=test_ds.column_names
    )
)

Map:   0%|          | 0/94076 [00:00<?, ? examples/s]

Map:   0%|          | 0/11760 [00:00<?, ? examples/s]

Map:   0%|          | 0/11760 [00:00<?, ? examples/s]

In [71]:
def inspect_tokenized_dataset(dataset, name):
    label_values = [
        label
        for row in dataset["labels"]
        for label in row
        if label != -100
    ]
    print(
        name,
        "rows=", len(dataset),
        "label_tokens=", len(label_values),
        "unique_labels=", sorted(set(label_values)),
        "non_background=", sum(label > 0 for label in label_values),
        "finite_labels=", all(np.isfinite(label_values))
    )

inspect_tokenized_dataset(tokenized_train, "train")
inspect_tokenized_dataset(tokenized_val, "validation")
inspect_tokenized_dataset(tokenized_test, "test")

parameter_values = [parameter.detach() for parameter in model.parameters()]
print(
    "model_finite=",
    all(torch.isfinite(parameter).all().item() for parameter in parameter_values)
)
print(
    "sample_labels=",
    tokenized_train[0]["labels"][:32]
)

train rows= 94076 label_tokens= 2648959 unique_labels= [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 19] non_background= 551077 finite_labels= True
validation rows= 11760 label_tokens= 331916 unique_labels= [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 19] non_background= 69285 finite_labels= True
test rows= 11760 label_tokens= 333443 unique_labels= [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 19] non_background= 69651 finite_labels= True
model_finite= True
sample_labels= [-100, 0, 0, 0, 0, 3, -100, -100, -100]

In [24]:
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support
)

print("Using sklearn token-level entity metrics")

Using sklearn token-level entity metrics

In [39]:
def _bio_spans(label_ids):
    spans = set()
    start = None
    entity_type = None

    for index, label_id in enumerate(list(label_ids) + [0]):
        label = id2label.get(int(label_id), "O")
        if label.startswith("B-"):
            if start is not None:
                spans.add((start, index, entity_type))
            start = index
            entity_type = label[2:]
        elif label.startswith("I-") and start is not None and entity_type == label[2:]:
            continue
        else:
            if start is not None:
                spans.add((start, index, entity_type))
            start = None
            entity_type = None

    return spans


def compute_metrics(prediction):
    logits, labels = prediction
    predictions = np.argmax(logits, axis=-1)

    true_positive = 0
    predicted_total = 0
    gold_total = 0
    per_label_counts = {
        label: {"tp": 0, "predicted": 0, "gold": 0}
        for label in LABEL_TYPES
    }

    for prediction_row, label_row in zip(predictions, labels):
        valid_positions = [index for index, label_id in enumerate(label_row) if label_id != -100]
        gold_ids = [label_row[index] for index in valid_positions]
        predicted_ids = [prediction_row[index] for index in valid_positions]

        gold_spans = _bio_spans(gold_ids)
        predicted_spans = _bio_spans(predicted_ids)
        matched_spans = gold_spans & predicted_spans

        true_positive += len(matched_spans)
        predicted_total += len(predicted_spans)
        gold_total += len(gold_spans)

        for start, end, label in predicted_spans:
            per_label_counts[label]["predicted"] += 1
        for start, end, label in gold_spans:
            per_label_counts[label]["gold"] += 1
        for start, end, label in matched_spans:
            per_label_counts[label]["tp"] += 1

    precision = true_positive / predicted_total if predicted_total else 0.0
    recall = true_positive / gold_total if gold_total else 0.0
    f1 = (
        2 * precision * recall / (precision + recall)
        if precision + recall
        else 0.0
    )

    metrics = {
        "precision": float(precision),
        "recall": float(recall),
        "f1": float(f1),
        "entity_count": float(gold_total),
    }

    for label, counts in per_label_counts.items():
        label_precision = (
            counts["tp"] / counts["predicted"]
            if counts["predicted"] else 0.0
        )
        label_recall = (
            counts["tp"] / counts["gold"]
            if counts["gold"] else 0.0
        )
        label_f1 = (
            2 * label_precision * label_recall / (label_precision + label_recall)
            if label_precision + label_recall
            else 0.0
        )
        metrics[f"f1_{label.lower()}"] = float(label_f1)

    return metrics

print("Using strict entity-span metrics")

Using strict entity-span metrics

In [26]:
from transformers import (
    DataCollatorForTokenClassification
)

data_collator = (
    DataCollatorForTokenClassification(
        tokenizer=tokenizer
    )
)

In [68]:
from transformers import TrainingArguments

use_cuda = torch.cuda.is_available()
compute_capability = (
    torch.cuda.get_device_capability(0)
    if use_cuda
    else (0, 0)
)

# AdamW is numerically unstable in this CUDA runtime; use stable SGD for this run.
use_fp16 = False
use_bf16 = False

training_args = TrainingArguments(
    output_dir=str(CHECKPOINT_DIR),
    learning_rate=1e-2,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=16,
    num_train_epochs=1,
    weight_decay=0.01,
    warmup_steps=500,
    max_grad_norm=1.0,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_steps=100,
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    greater_is_better=True,
    fp16=use_fp16,
    bf16=use_bf16,
    gradient_checkpointing=False,
    report_to="none",
    save_total_limit=2,
    seed=SEED
)

print(
    "Training device:",
    "cuda" if use_cuda else "cpu",
    "compute capability:",
    compute_capability,
    "optimizer:",
    "SGD",
    "fp16:",
    use_fp16,
    "bf16:",
    use_bf16
)

Training device: cuda compute capability: (7, 5) optimizer: SGD fp16: False bf16: False

In [69]:
from transformers import Trainer

stable_optimizer = torch.optim.SGD(
    model.parameters(),
    lr=training_args.learning_rate,
    momentum=0.9,
    weight_decay=training_args.weight_decay
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_val,
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
    optimizers=(stable_optimizer, None)
)

print("Trainer ready with stable SGD optimizer")

Trainer ready with stable SGD optimizer

In [70]:
trainer.train()

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 2, 'bos_token_id': 1}.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=11760, training_loss=0.08260949079682227, metrics={'train_runtime': 793.0182, 'train_samples_per_second': 118.63, 'train_steps_per_second': 14.829, 'total_flos': 2799697861623960.0, 'train_loss': 0.08260949079682227, 'epoch': 1.0})

In [72]:
test_metrics = trainer.evaluate(
    tokenized_test
)

print(
    json.dumps(
        test_metrics,
        indent=2
    )
)

{
  "eval_loss": 0.021697998046875,
  "eval_precision": 0.984694818366218,
  "eval_recall": 0.9845586540677576,
  "eval_f1": 0.9846267315094382,
  "eval_entity_count": 43390.0,
  "eval_f1_person": 0.9846527232493398,
  "eval_f1_location": 0.9958068767221756,
  "eval_f1_address": 0.9973564047104061,
  "eval_f1_organization": 0.037940379403794036,
  "eval_f1_email": 0.9778970634670034,
  "eval_f1_phone": 0.9873077861850135,
  "eval_f1_card": 0.997997432605905,
  "eval_f1_ip_address": 0.8867357166722352,
  "eval_f1_url": 0.0,
  "eval_f1_secret": 0.9926362297496318
}

In [3]:
from pathlib import Path

MODEL_DIR = globals().get("MODEL_DIR", Path.cwd() / "client_models" / "pii_ner")
BEST_MODEL_DIR = MODEL_DIR / "best"
BEST_MODEL_DIR.mkdir(parents=True, exist_ok=True)

if "trainer" not in globals() or "tokenizer" not in globals():
    print("Warning: trainer/tokenizer are not defined in the current notebook state.")
    print("Run the model training cells before saving the best model.")
    print(f"Prepared output directory: {BEST_MODEL_DIR}")
else:
    trainer.save_model(str(BEST_MODEL_DIR))
    tokenizer.save_pretrained(str(BEST_MODEL_DIR))
    print(BEST_MODEL_DIR)

Warning: trainer/tokenizer are not defined in the current notebook state.
Run the model training cells before saving the best model.
Prepared output directory: /content/client_models/pii_ner/best

In [77]:
from transformers import pipeline

inference_device = 0 if torch.cuda.is_available() else -1

ner = pipeline(
    "token-classification",
    model=str(BEST_MODEL_DIR),
    tokenizer=str(BEST_MODEL_DIR),
    aggregation_strategy="simple",
    device=inference_device
)

print("Inference device:", inference_device)

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

Inference device: 0

In [75]:
tests = [
    "Aarav Sharma submitted the scholarship application.",

    "The applicant lives in Bengaluru, Karnataka.",

    "Please contact Rahul Mehta regarding the application.",

    "The student studies at Indian Institute of Technology Delhi."
]


for text in tests:

    print(
        "\nTEXT:",
        text
    )

    print(
        ner(text)
    )

TEXT: Aarav Sharma submitted the scholarship application.
[{'entity_group': 'ADDRESS', 'score': np.float32(0.67088115), 'word': 'Aarav Sharma submitted', 'start': 0, 'end': 22}, {'entity_group': 'LOCATION', 'score': np.float32(0.96061987), 'word': 'scholarship', 'start': 26, 'end': 38}, {'entity_group': 'ADDRESS', 'score': np.float32(0.84152687), 'word': 'application', 'start': 38, 'end': 50}]

TEXT: The applicant lives in Bengaluru, Karnataka.
[{'entity_group': 'LOCATION', 'score': np.float32(0.54501), 'word': 'The', 'start': 0, 'end': 3}, {'entity_group': 'ADDRESS', 'score': np.float32(0.76166964), 'word': 'applicant lives', 'start': 3, 'end': 19}, {'entity_group': 'LOCATION', 'score': np.float32(0.96696544), 'word': 'Bengaluru', 'start': 22, 'end': 32}, {'entity_group': 'ADDRESS', 'score': np.float32(0.28370607), 'word': 'Karnataka', 'start': 33, 'end': 43}]

TEXT: Please contact Rahul Mehta regarding the application.
[{'entity_group': 'LOCATION', 'score': np.float32(0.5438165), 'word': 'Please', 'start': 0, 'end': 6}, {'entity_group': 'PERSON', 'score': np.float32(0.9749131), 'word': 'Rahul', 'start': 14, 'end': 20}, {'entity_group': 'ADDRESS', 'score': np.float32(0.9293242), 'word': 'Mehta regarding', 'start': 20, 'end': 36}, {'entity_group': 'PERSON', 'score': np.float32(0.7160509), 'word': 'application', 'start': 40, 'end': 52}]

TEXT: The student studies at Indian Institute of Technology Delhi.
[{'entity_group': 'LOCATION', 'score': np.float32(0.5438404), 'word': 'The', 'start': 0, 'end': 3}, {'entity_group': 'ADDRESS', 'score': np.float32(0.815342), 'word': 'student studies at Indian Institute of Technology Delhi', 'start': 3, 'end': 59}]

In [76]:
ONNX_DIR = (
    MODEL_DIR /
    "onnx"
)

ONNX_DIR.mkdir(
    parents=True,
    exist_ok=True
)

In [79]:
import subprocess

export_command = [
    "optimum-cli",
    "export",
    "onnx",
    "--model",
    str(BEST_MODEL_DIR),
    "--task",
    "token-classification",
    str(ONNX_DIR)
]

result = subprocess.run(
    export_command,
    check=False,
    capture_output=True,
    text=True
)

print("Return code:", result.returncode)
print(result.stdout)
print(result.stderr)
if result.returncode != 0:
    raise RuntimeError("ONNX export failed; see exporter diagnostics above")

Return code: 2

usage: optimum-cli
Optimum CLI tool: error: unrecognized arguments: onnx --model /content/client_models/pii_ner/best --task token-classification /content/client_models/pii_ner/onnx

RuntimeError: ONNX export failed; see exporter diagnostics above

In [ ]:
list(
    ONNX_DIR.iterdir()
)

In [ ]:
import onnx

model_files = list(
    ONNX_DIR.glob("*.onnx")
)

assert model_files, (
    "No ONNX model produced"
)

onnx_model = onnx.load(
    str(model_files[0])
)

onnx.checker.check_model(
    onnx_model
)

print(
    "ONNX valid:",
    model_files[0]
)

In [80]:
from collections import Counter
from datetime import datetime


def _safe_float(value):
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _metric_value(metrics, key):
    value = metrics.get(key)
    return _safe_float(value)


# ========================= FINAL MODEL EVALUATION REPORT =========================
report_timestamp = datetime.now().astimezone().isoformat(timespec="seconds")

label_token_counts = Counter()
for row in test_ds["ner_tags"]:
    label_token_counts.update(tag for tag in row if tag != "O")

entity_support = Counter()
for row in test_ds["ner_tags"]:
    open_entity = None
    for tag in list(row) + ["O"]:
        if tag.startswith("B-"):
            entity_support[tag[2:]] += 1
            open_entity = tag[2:]
        elif tag.startswith("I-"):
            continue
        else:
            open_entity = None

log_history = getattr(trainer.state, "log_history", [])
training_logs = [
    entry for entry in log_history
    if "loss" in entry and "eval_loss" not in entry
]
evaluation_logs = [
    entry for entry in log_history
    if "eval_loss" in entry
]
last_training_log = training_logs[-1] if training_logs else {}
last_evaluation_log = evaluation_logs[-1] if evaluation_logs else {}

final_metrics = dict(test_metrics) if isinstance(test_metrics, dict) else {}
final_metrics.setdefault("eval_loss", last_evaluation_log.get("eval_loss"))

parameter_finiteness = all(
    torch.isfinite(parameter.detach()).all().item()
    for parameter in model.parameters()
)
onnx_files = list(ONNX_DIR.glob("*.onnx")) if ONNX_DIR.exists() else []

report = {
    "report": {
        "generated_at": report_timestamp,
        "status": "PASS" if parameter_finiteness and _metric_value(final_metrics, "eval_f1") is not None else "INCOMPLETE",
        "base_model": BASE_MODEL,
        "saved_model": str(BEST_MODEL_DIR),
        "onnx_files": [str(path) for path in onnx_files],
        "onnx_export_status": "AVAILABLE" if onnx_files else "NOT_AVAILABLE",
    },
    "data": {
        "source_rows": len(normalized_records),
        "plain_language_rows": len(plain_language_records),
        "combined_rows": len(normalized),
        "train_rows": len(train_ds),
        "validation_rows": len(val_ds),
        "test_rows": len(test_ds),
        "test_entity_count": int(sum(entity_support.values())),
        "label_token_support": dict(sorted(label_token_counts.items())),
        "entity_support": dict(sorted(entity_support.items())),
    },
    "training": {
        "device": "cuda" if use_cuda else "cpu",
        "cuda_device": torch.cuda.get_device_name(0) if use_cuda else None,
        "compute_capability": compute_capability,
        "optimizer": "SGD",
        "learning_rate": _safe_float(training_args.learning_rate),
        "epochs": _safe_float(training_args.num_train_epochs),
        "batch_size": training_args.per_device_train_batch_size,
        "weight_decay": _safe_float(training_args.weight_decay),
        "warmup_steps": training_args.warmup_steps,
        "max_grad_norm": _safe_float(training_args.max_grad_norm),
        "fp16": bool(training_args.fp16),
        "bf16": bool(training_args.bf16),
        "gradient_checkpointing": bool(training_args.gradient_checkpointing),
        "global_steps": trainer.state.global_step,
        "training_loss": _safe_float(last_training_log.get("loss")),
        "train_runtime_seconds": _safe_float(
            trainer.state.log_history[-1].get("train_runtime")
            if trainer.state.log_history and "train_runtime" in trainer.state.log_history[-1]
            else None
        ),
    },
    "test_metrics": {
        "loss": _metric_value(final_metrics, "eval_loss"),
        "precision": _metric_value(final_metrics, "eval_precision"),
        "recall": _metric_value(final_metrics, "eval_recall"),
        "strict_entity_f1": _metric_value(final_metrics, "eval_f1"),
        "entity_count": _metric_value(final_metrics, "eval_entity_count"),
        "accuracy": _metric_value(final_metrics, "eval_accuracy"),
        "per_label_f1": {
            label: _metric_value(final_metrics, f"eval_f1_{label.lower()}")
            for label in LABEL_TYPES
        },
    },
    "health_checks": {
        "model_parameters_finite": parameter_finiteness,
        "test_loss_finite": (
            _metric_value(final_metrics, "eval_loss") is not None
            and np.isfinite(_metric_value(final_metrics, "eval_loss"))
        ),
        "strict_f1_finite": (
            _metric_value(final_metrics, "eval_f1") is not None
            and np.isfinite(_metric_value(final_metrics, "eval_f1"))
        ),
        "tokenizer_vocab_size": len(tokenizer),
        "model_parameter_count": sum(parameter.numel() for parameter in model.parameters()),
    },
    "known_limitations": [
        "URL has no reliable held-out F1 in the current WebPII-derived labels.",
        "Organization support is weaker than the other entity classes.",
        "Free-text inference should use confidence thresholds and hard-negative calibration before production redaction.",
        "ONNX export is unavailable until the installed optimum-cli syntax/version is corrected.",
    ],
}

print("=" * 88)
print("FINAL ON-DEVICE PII MODEL EVALUATION REPORT")
print("=" * 88)
print(json.dumps(report, indent=2, default=str))
print("=" * 88)
print("PRIMARY RESULTS")
print(
    f"Strict entity F1 : {report['test_metrics']['strict_entity_f1']:.4f}"
    if report["test_metrics"]["strict_entity_f1"] is not None
    else "Strict entity F1 : unavailable"
)
print(
    f"Precision        : {report['test_metrics']['precision']:.4f}"
    if report["test_metrics"]["precision"] is not None
    else "Precision        : unavailable"
)
print(
    f"Recall           : {report['test_metrics']['recall']:.4f}"
    if report["test_metrics"]["recall"] is not None
    else "Recall           : unavailable"
)
print("Parameters finite:", report["health_checks"]["model_parameters_finite"])
print("ONNX status      :", report["report"]["onnx_export_status"])
print("=" * 88)

========================================================================================
FINAL ON-DEVICE PII MODEL EVALUATION REPORT
========================================================================================
{
  "report": {
    "generated_at": "2026-09-29T09:06:52+00:00",
    "status": "PASS",
    "base_model": "microsoft/deberta-v3-small",
    "saved_model": "/content/client_models/pii_ner/best",
    "onnx_files": [],
    "onnx_export_status": "NOT_AVAILABLE"
  },
  "data": {
    "source_rows": 40384,
    "plain_language_rows": 77212,
    "combined_rows": 117596,
    "train_rows": 94076,
    "validation_rows": 11760,
    "test_rows": 11760,
    "test_entity_count": 43432,
    "label_token_support": {
      "B-ADDRESS": 4161,
      "B-CARD": 9733,
      "B-EMAIL": 3114,
      "B-IP_ADDRESS": 1409,
      "B-LOCATION": 12545,
      "B-ORGANIZATION": 359,
      "B-PERSON": 7003,
      "B-PHONE": 4097,
      "B-SECRET": 1011,
      "I-ADDRESS": 11624,
      "I-CARD": 5246,
      "I-IP_ADDRESS": 3940,
      "I-LOCATION": 5980,
      "I-ORGANIZATION": 521,
      "I-PERSON": 1817,
      "I-PHONE": 44
    },
    "entity_support": {
      "ADDRESS": 4161,
      "CARD": 9733,
      "EMAIL": 3114,
      "IP_ADDRESS": 1409,
      "LOCATION": 12545,
      "ORGANIZATION": 359,
      "PERSON": 7003,
      "PHONE": 4097,
      "SECRET": 1011
    }
  },
  "training": {
    "device": "cuda",
    "cuda_device": "Tesla T4",
    "compute_capability": [
      7,
      5
    ],
    "optimizer": "SGD",
    "learning_rate": 0.01,
    "epochs": 1.0,
    "batch_size": 8,
    "weight_decay": 0.01,
    "warmup_steps": 500,
    "max_grad_norm": 1.0,
    "fp16": false,
    "bf16": false,
    "gradient_checkpointing": false,
    "global_steps": 11760,
    "training_loss": 0.040308685302734376,
    "train_runtime_seconds": null
  },
  "test_metrics": {
    "loss": 0.021697998046875,
    "precision": 0.984694818366218,
    "recall": 0.9845586540677576,
    "strict_entity_f1": 0.9846267315094382,
    "entity_count": 43390.0,
    "accuracy": null,
    "per_label_f1": {
      "PERSON": 0.9846527232493398,
      "LOCATION": 0.9958068767221756,
      "ADDRESS": 0.9973564047104061,
      "ORGANIZATION": 0.037940379403794036,
      "EMAIL": 0.9778970634670034,
      "PHONE": 0.9873077861850135,
      "CARD": 0.997997432605905,
      "IP_ADDRESS": 0.8867357166722352,
      "URL": 0.0,
      "SECRET": 0.9926362297496318
    }
  },
  "health_checks": {
    "model_parameters_finite": true,
    "test_loss_finite": "True",
    "strict_f1_finite": "True",
    "tokenizer_vocab_size": 128001,
    "model_parameter_count": 141320469
  },
  "known_limitations": [
    "URL has no reliable held-out F1 in the current WebPII-derived labels.",
    "Organization support is weaker than the other entity classes.",
    "Free-text inference should use confidence thresholds and hard-negative calibration before production redaction.",
    "ONNX export is unavailable until the installed optimum-cli syntax/version is corrected."
  ]
}
========================================================================================
PRIMARY RESULTS
Strict entity F1 : 0.9846
Precision        : 0.9847
Recall           : 0.9846
Parameters finite: True
ONNX status      : NOT_AVAILABLE
========================================================================================

In [81]:
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    precision_recall_fscore_support
)

# ========================= MODEL PERFORMANCE METRICS =========================
performance_prediction = trainer.predict(tokenized_test)
performance_logits = performance_prediction.predictions
performance_labels = performance_prediction.label_ids
performance_predictions = np.argmax(performance_logits, axis=-1)

valid_mask = performance_labels != -100
flat_true = performance_labels[valid_mask].astype(int)
flat_pred = performance_predictions[valid_mask].astype(int)
metric_ids = list(range(len(LABELS)))
metric_names = [id2label[index] for index in metric_ids]

accuracy = accuracy_score(flat_true, flat_pred)
macro_precision, macro_recall, macro_f1, _ = precision_recall_fscore_support(
    flat_true,
    flat_pred,
    labels=metric_ids,
    average="macro",
    zero_division=0
)
weighted_precision, weighted_recall, weighted_f1, _ = precision_recall_fscore_support(
    flat_true,
    flat_pred,
    labels=metric_ids,
    average="weighted",
    zero_division=0
)
per_class_precision, per_class_recall, per_class_f1, per_class_support = (
    precision_recall_fscore_support(
        flat_true,
        flat_pred,
        labels=metric_ids,
        average=None,
        zero_division=0
    )
)

performance_report = classification_report(
    flat_true,
    flat_pred,
    labels=metric_ids,
    target_names=metric_names,
    output_dict=True,
    zero_division=0
)

performance_matrix = confusion_matrix(
    flat_true,
    flat_pred,
    labels=metric_ids
)
row_totals = performance_matrix.sum(axis=1, keepdims=True)
normalized_matrix = np.divide(
    performance_matrix,
    row_totals,
    out=np.zeros_like(performance_matrix, dtype=float),
    where=row_totals != 0
)

per_label_metrics = {}
for index, label_name in enumerate(metric_names):
    per_label_metrics[label_name] = {
        "precision": float(per_class_precision[index]),
        "recall": float(per_class_recall[index]),
        "f1": float(per_class_f1[index]),
        "support": int(per_class_support[index])
    }

performance_metrics = {
    "evaluation_split": "test",
    "evaluated_tokens": int(len(flat_true)),
    "overall": {
        "token_accuracy": float(accuracy),
        "macro_precision": float(macro_precision),
        "macro_recall": float(macro_recall),
        "macro_f1": float(macro_f1),
        "weighted_precision": float(weighted_precision),
        "weighted_recall": float(weighted_recall),
        "weighted_f1": float(weighted_f1),
        "strict_entity_precision": _metric_value(test_metrics, "eval_precision"),
        "strict_entity_recall": _metric_value(test_metrics, "eval_recall"),
        "strict_entity_f1": _metric_value(test_metrics, "eval_f1"),
        "test_loss": _metric_value(test_metrics, "eval_loss")
    },
    "per_label": per_label_metrics,
    "confusion_matrix_labels": metric_names,
    "confusion_matrix": performance_matrix.tolist(),
    "normalized_confusion_matrix": normalized_matrix.round(4).tolist(),
    "classification_report": performance_report
}

print("=" * 100)
print("MODEL PERFORMANCE METRICS - HELD-OUT TEST SET")
print("=" * 100)
print(json.dumps(performance_metrics["overall"], indent=2))
print("\nPER-LABEL PERFORMANCE")
print(
    f"{'LABEL':<18} {'PRECISION':>10} {'RECALL':>10} "
    f"{'F1':>10} {'SUPPORT':>10}"
)
print("-" * 64)
for label_name, metrics in per_label_metrics.items():
    print(
        f"{label_name:<18} "
        f"{metrics['precision']:>10.4f} "
        f"{metrics['recall']:>10.4f} "
        f"{metrics['f1']:>10.4f} "
        f"{metrics['support']:>10d}"
    )
print("\nNORMALIZED CONFUSION MATRIX LABEL ORDER")
print(metric_names)
print(np.array(performance_metrics["normalized_confusion_matrix"]))
print("\nFULL MACHINE-READABLE METRICS")
print(json.dumps(performance_metrics, indent=2))

====================================================================================================
MODEL PERFORMANCE METRICS - HELD-OUT TEST SET
====================================================================================================
{
  "token_accuracy": 0.9973548702476885,
  "macro_precision": 0.7486643738097809,
  "macro_recall": 0.6872542195868394,
  "macro_f1": 0.6924756521020101,
  "weighted_precision": 0.9973394620906296,
  "weighted_recall": 0.9973548702476885,
  "weighted_f1": 0.9967469961165595,
  "strict_entity_precision": 0.984694818366218,
  "strict_entity_recall": 0.9845586540677576,
  "strict_entity_f1": 0.9846267315094382,
  "test_loss": 0.021697998046875
}

PER-LABEL PERFORMANCE
LABEL               PRECISION     RECALL         F1    SUPPORT
----------------------------------------------------------------
O                      0.9994     1.0000     0.9997     263792
B-PERSON               0.9994     0.9999     0.9996       7003
I-PERSON               0.9890     0.9389     0.9633       1817
B-LOCATION             0.9994     1.0000     0.9997      12517
I-LOCATION             0.9958     0.9853     0.9905       4281
B-ADDRESS              1.0000     1.0000     1.0000       4161
I-ADDRESS              0.9900     0.9987     0.9943      11438
B-ORGANIZATION         1.0000     0.0279     0.0542        359
I-ORGANIZATION         1.0000     0.5360     0.6979        375
B-EMAIL                0.9618     0.9945     0.9779       3114
I-EMAIL                0.0000     0.0000     0.0000          0
B-PHONE                0.9980     0.9980     0.9980       4097
I-PHONE                0.0000     0.0000     0.0000         44
B-CARD                 0.9991     1.0000     0.9995       9733
I-CARD                 0.9956     0.9969     0.9963       4820
B-IP_ADDRESS           0.8448     0.9677     0.9021       1395
I-IP_ADDRESS           0.9642     0.9885     0.9762       3486
B-URL                  0.0000     0.0000     0.0000          0
I-URL                  0.0000     0.0000     0.0000          0
B-SECRET               0.9854     1.0000     0.9926       1011
I-SECRET               0.0000     0.0000     0.0000          0

NORMALIZED CONFUSION MATRIX LABEL ORDER
['O', 'B-PERSON', 'I-PERSON', 'B-LOCATION', 'I-LOCATION', 'B-ADDRESS', 'I-ADDRESS', 'B-ORGANIZATION', 'I-ORGANIZATION', 'B-EMAIL', 'I-EMAIL', 'B-PHONE', 'I-PHONE', 'B-CARD', 'I-CARD', 'B-IP_ADDRESS', 'I-IP_ADDRESS', 'B-URL', 'I-URL', 'B-SECRET', 'I-SECRET']
[[1.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 9.999e-01 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 1.000e-04 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [5.670e-02 0.000e+00 9.389e-01 0.000e+00 0.000e+00 0.000e+00 4.400e-03
  0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 1.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [5.800e-03 0.000e+00 0.000e+00 1.400e-03 9.853e-01 0.000e+00 5.400e-03
  0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  5.000e-04 0.000e+00 1.600e-03 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 1.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [8.000e-04 0.000e+00 0.000e+00 0.000e+00 1.000e-04 0.000e+00 9.987e-01
  0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  1.000e-04 0.000e+00 3.000e-04 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 1.110e-02 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  2.790e-02 0.000e+00 3.343e-01 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 6.267e-01 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 5.070e-02 0.000e+00 0.000e+00 0.000e+00 2.187e-01
  0.000e+00 5.360e-01 2.700e-03 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 1.920e-01 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [5.500e-03 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 9.945e-01 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 2.000e-04 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00 0.000e+00 9.980e-01 0.000e+00 1.700e-03
  0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 4.550e-02
  0.000e+00 0.000e+00 2.270e-02 0.000e+00 1.818e-01 0.000e+00 0.000e+00
  4.091e-01 0.000e+00 0.000e+00 0.000e+00 0.000e+00 3.409e-01 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 1.000e+00
  0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [2.700e-03 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 4.000e-04
  9.969e-01 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 9.677e-01 3.230e-02 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 4.900e-03 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 6.600e-03 9.885e-01 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 1.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]]

FULL MACHINE-READABLE METRICS
{
  "evaluation_split": "test",
  "evaluated_tokens": 333443,
  "overall": {
    "token_accuracy": 0.9973548702476885,
    "macro_precision": 0.7486643738097809,
    "macro_recall": 0.6872542195868394,
    "macro_f1": 0.6924756521020101,
    "weighted_precision": 0.9973394620906296,
    "weighted_recall": 0.9973548702476885,
    "weighted_f1": 0.9967469961165595,
    "strict_entity_precision": 0.984694818366218,
    "strict_entity_recall": 0.9845586540677576,
    "strict_entity_f1": 0.9846267315094382,
    "test_loss": 0.021697998046875
  },
  "per_label": {
    "O": {
      "precision": 0.9993673259862327,
      "recall": 1.0,
      "f1": 0.9996835628923488,
      "support": 263792
    },
    "B-PERSON": {
      "precision": 0.9994290608050242,
      "recall": 0.9998572040554048,
      "f1": 0.9996430865871939,
      "support": 7003
    },
    "I-PERSON": {
      "precision": 0.9889855072463768,
      "recall": 0.9389102916895983,
      "f1": 0.9632975719932242,
      "support": 1817
    },
    "B-LOCATION": {
      "precision": 0.999441073139572,
      "recall": 1.0,
      "f1": 0.999720458448145,
      "support": 12517
    },
    "I-LOCATION": {
      "precision": 0.9957507082152974,
      "recall": 0.9852838121934128,
      "f1": 0.9904896090172596,
      "support": 4281
    },
    "B-ADDRESS": {
      "precision": 1.0,
      "recall": 1.0,
      "f1": 1.0,
      "support": 4161
    },
    "I-ADDRESS": {
      "precision": 0.9900329346507194,
      "recall": 0.998688581919916,
      "f1": 0.994341922005571,
      "support": 11438
    },
    "B-ORGANIZATION": {
      "precision": 1.0,
      "recall": 0.027855153203342618,
      "f1": 0.05420054200542006,
      "support": 359
    },
    "I-ORGANIZATION": {
      "precision": 1.0,
      "recall": 0.536,
      "f1": 0.6979166666666666,
      "support": 375
    },
    "B-EMAIL": {
      "precision": 0.9618012422360248,
      "recall": 0.9945407835581246,
      "f1": 0.9778970634670034,
      "support": 3114
    },
    "I-EMAIL": {
      "precision": 0.0,
      "recall": 0.0,
      "f1": 0.0,
      "support": 0
    },
    "B-PHONE": {
      "precision": 0.9980473517207713,
      "recall": 0.9980473517207713,
      "f1": 0.9980473517207713,
      "support": 4097
    },
    "I-PHONE": {
      "precision": 0.0,
      "recall": 0.0,
      "f1": 0.0,
      "support": 44
    },
    "B-CARD": {
      "precision": 0.9990761650585095,
      "recall": 1.0,
      "f1": 0.9995378690629012,
      "support": 9733
    },
    "I-CARD": {
      "precision": 0.9956485702445089,
      "recall": 0.9968879668049793,
      "f1": 0.9962678830603359,
      "support": 4820
    },
    "B-IP_ADDRESS": {
      "precision": 0.8448060075093867,
      "recall": 0.967741935483871,
      "f1": 0.9021049114600735,
      "support": 1395
    },
    "I-IP_ADDRESS": {
      "precision": 0.9641857862339116,
      "recall": 0.9885255306942053,
      "f1": 0.9762039660056657,
      "support": 3486
    },
    "B-URL": {
      "precision": 0.0,
      "recall": 0.0,
      "f1": 0.0,
      "support": 0
    },
    "I-URL": {
      "precision": 0.0,
      "recall": 0.0,
      "f1": 0.0,
      "support": 0
    },
    "B-SECRET": {
      "precision": 0.9853801169590644,
      "recall": 1.0,
      "f1": 0.9926362297496318,
      "support": 1011
    },
    "I-SECRET": {
      "precision": 0.0,
      "recall": 0.0,
      "f1": 0.0,
      "support": 0
    }
  },
  "confusion_matrix_labels": [
    "O",
    "B-PERSON",
    "I-PERSON",
    "B-LOCATION",
    "I-LOCATION",
    "B-ADDRESS",
    "I-ADDRESS",
    "B-ORGANIZATION",
    "I-ORGANIZATION",
    "B-EMAIL",
    "I-EMAIL",
    "B-PHONE",
    "I-PHONE",
    "B-CARD",
    "I-CARD",
    "B-IP_ADDRESS",
    "I-IP_ADDRESS",
    "B-URL",
    "I-URL",
    "B-SECRET",
    "I-SECRET"
  ],
  "confusion_matrix": [
    [
      263792,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    [
      0,
      7002,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    [
      103,
      0,
      1706,
      0,
      0,
      0,
      8,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    [
      0,
      0,
      0,
      12517,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    [
      25,
      0,
      0,
      6,
      4218,
      0,
      23,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      2,
      0,
      7,
      0,
      0,
      0,
      0
    ],
    [
      0,
      0,
      0,
      0,
      0,
      4161,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    [
      9,
      0,
      0,
      0,
      1,
      0,
      11423,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      0,
      4,
      0,
      0,
      0,
      0
    ],
    [
      0,
      4,
      0,
      0,
      0,
      0,
      0,
      10,
      0,
      120,
      0,
      0,
      0,
      0,
      0,
      225,
      0,
      0,
      0,
      0,
      0
    ],
    [
      0,
      0,
      19,
      0,
      0,
      0,
      82,
      0,
      201,
      1,
      0,
      0,
      0,
      0,
      0,
      0,
      72,
      0,
      0,
      0,
      0
    ],
    [
      17,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      3097,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    [
      0,
      0,
      0,
      1,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      4089,
      0,
      7,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    [
      0,
      0,
      0,
      0,
      0,
      0,
      2,
      0,
      0,
      1,
      0,
      8,
      0,
      0,
      18,
      0,
      0,
      0,
      0,
      15,
      0
    ],
    [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      9733,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    [
      13,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      2,
      4805,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1350,
      45,
      0,
      0,
      0,
      0
    ],
    [
      0,
      0,
      0,
      0,
      17,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      23,
      3446,
      0,
      0,
      0,
      0
    ],
    [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1011,
      0
    ],
    [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ]
  ],
  "normalized_confusion_matrix": [
    [
      1.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0
    ],
    [
      0.0,
      0.9999,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0001,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0
    ],
    [
      0.0567,
      0.0,
      0.9389,
      0.0,
      0.0,
      0.0,
      0.0044,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0
    ],
    [
      0.0,
      0.0,
      0.0,
      1.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0
    ],
    [
      0.0058,
      0.0,
      0.0,
      0.0014,
      0.9853,
      0.0,
      0.0054,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0005,
      0.0,
      0.0016,
      0.0,
      0.0,
      0.0,
      0.0
    ],
    [
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      1.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0
    ],
    [
      0.0008,
      0.0,
      0.0,
      0.0,
      0.0001,
      0.0,
      0.9987,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0001,
      0.0,
      0.0003,
      0.0,
      0.0,
      0.0,
      0.0
    ],
    [
      0.0,
      0.0111,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0279,
      0.0,
      0.3343,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.6267,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0
    ],
    [
      0.0,
      0.0,
      0.0507,
      0.0,
      0.0,
      0.0,
      0.2187,
      0.0,
      0.536,
      0.0027,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.192,
      0.0,
      0.0,
      0.0,
      0.0
    ],
    [
      0.0055,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.9945,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0
    ],
    [
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0
    ],
    [
      0.0,
      0.0,
      0.0,
      0.0002,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.998,
      0.0,
      0.0017,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0
    ],
    [
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0455,
      0.0,
      0.0,
      0.0227,
      0.0,
      0.1818,
      0.0,
      0.0,
      0.4091,
      0.0,
      0.0,
      0.0,
      0.0,
      0.3409,
      0.0
    ],
    [
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      1.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0
    ],
    [
      0.0027,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0004,
      0.9969,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0
    ],
    [
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.9677,
      0.0323,
      0.0,
      0.0,
      0.0,
      0.0
    ],
    [
      0.0,
      0.0,
      0.0,
      0.0,
      0.0049,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0066,
      0.9885,
      0.0,
      0.0,
      0.0,
      0.0
    ],
    [
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0
    ],
    [
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0
    ],
    [
      0.0,
      0.0,
      0.0,
      0.0,